### ISSUE TITLE
[BUG] Unable to show backups via PBS

### ISSUE THREAD

**Issue by pluusla** [rcourtman/Pulse#105]
**Describe the bug**
Pulse is unable to display backup information from Proxmox Backup Server (PBS) in the "Backups" tab. The "Diagnostics" tab shows a [WARNING] PBS Data: PBS is configured but no backups were found. Verify that backups exist in your PBS datastores and that the API token has permission to read them. message, despite backups existing and PBS itself functioning correctly (e.g., displaying verification jobs).

**To Reproduce**

1. Steps to reproduce the behavior:
2. Configure Pulse with a Proxmox Backup Server, providing the correct hostname and an API token.
3. Assign the Audit role to the API token on the PBS.
4. Assign the PVEAuditor role to the API tokens for Proxmox VE servers.
5. (Optional, but configured by user): Assign PVEDatastoreAdmin role to API tokens for all three servers (PVEs and PBS) on their respective storages.
6. Navigate to the "Backups" tab in Pulse.
7. Observe that no backup information is displayed.
8. Navigate to the "Diagnostics" tab.
9. Observe the warning message: [WARNING] PBS Data: PBS is configured but no backups were found. Verify that backups exist in your PBS datastores and that the API token has permission to read them.

**Expected behavior**
Pulse should display existing backup jobs and their status from the configured Proxmox Backup Server in the "Backups" tab. The diagnostics warning regarding missing backups should not appear.

**Screenshots**

**Environment (please complete the following information):**
 - Pulse Version: 3.17.3
 - Proxmox VE Version: 8.4.1
 - Browser: Brave latest
 - OS Hosting Pulse: LXC on Proxmox

**Additional context**
I have configured the Proxmox Backup Server (PBS) API token with the Audit role. For my Proxmox VE servers, the API tokens are configured with the PVEAuditor role. Additionally, I have assigned the PVEDatastoreAdmin role to the respective API tokens for storage access on all three servers (two PVEs and one PBS).

My understanding was that the Audit role on PBS should be sufficient to list existing backups. However, the diagnostics message suggests a permission issue. It is possible that the Audit role in PBS does not grant sufficient privileges to read or list the contents of the datastores where backups are stored, even if it allows verification job visibility. It might require Datastore.Audit or Datastore.Read privileges directly on the datastore path.

And I use namespaces für my two PVE in PBS. Maybe a hint.

**Comment by rcourtman** [comment]
**Fixed in [4f4d38f](https://github.com/rcourtman/Pulse/commit/4f4d38f)**

Implemented PBS namespace support - Pulse now discovers and queries all namespaces in each datastore. This should resolve the empty Backups tab issue you were experiencing.

The fix is committed to main and will be in the next release. Thanks for the namespace detail - that was key to solving this!

**Comment by pluusla** [comment]
Many thanks for the quick solution! So I'll wait for the next release.

**Comment by pluusla** [comment]
Has this fix been released yet? I'm currently on version 3.28.2, but I still don't see any backups.

**Comment by rcourtman** [comment]
@pluusla Should be fixed, can you try [v3.30.0-rc3](https://github.com/rcourtman/Pulse/releases/tag/v3.30.0-rc3). If it's not working 
it's highly likely a permission issue with your token/user.

**Comment by pluusla** [comment]
> @pluusla Should be fixed, can you try [v3.30.0-rc3](https://github.com/rcourtman/Pulse/releases/tag/v3.30.0-rc3). If it's not working 
> it's highly likely a permission issue with your token/user. 

So, I installed the RC.

The Backup tab now shows health 100% and LXC under Recent.
But the list below with the guest names does not show me any backups. 

The same applies to the PBS tab. No data under Task Summary or the detailed Task Details.

The permissions should be correct. I created them exactly according to the instructions.

**Comment by rcourtman** [comment]
PBS support has been significantly improved in recent versions including better namespace handling. Can you try [v3.31.0](https://github.com/rcourtman/Pulse/releases/tag/v3.31.0)?

Make sure your PBS API token has the `Datastore.Audit` permission on the datastore paths.

**Comment by pluusla** [comment]
@rcourtman 

I have now checked the version. Unfortunately, it still does not show me any backups per container in the lower area, although it shows successful backup jobs in the upper area. I have set the Datastore.Audit authorization correctly in PBS

![Image](https://github.com/user-attachments/assets/f5ddfc49-37d8-4191-9803-79f2fe1c2c48)

**Comment by rcourtman** [comment]
v3.32.0 improves PBS namespace filtering. Can you try the latest version? If backups still don't appear, please share the diagnostics output.

**Comment by Sakreton** [comment]
I am having the same issue, using v3.32.0

![Image](https://github.com/user-attachments/assets/ad0df889-89e5-4c09-b342-d0710c974b7c)
Pulse correctly detects the datastore "Wablu_NFS" but no the backups themself.

[pulse_diagnostics_2025-06-28T07-06-47.json](https://github.com/user-attachments/files/20959278/pulse_diagnostics_2025-06-28T07-06-47.json)

**Comment by pluusla** [comment]
@rcourtman 

[pulse_diagnostics_2025-06-28T07-32-52.json](https://github.com/user-attachments/files/20959401/pulse_diagnostics_2025-06-28T07-32-52.json)

**Comment by rcourtman** [comment]
Thanks for the diagnostics @pluusla and @Sakreton. I see PBS is finding your 307 snapshots but not linking them to guests. This specific issue was addressed in [v3.33.0-rc1](https://github.com/rcourtman/Pulse/releases/tag/v3.33.0-rc1) with improved backup-to-guest mapping.

Can you try the latest RC and let me know if you're now seeing backups in the per-guest list? The diagnostics might look similar, but the backup display should be fixed.

**Comment by pluusla** [comment]
@rcourtman 
I have now installed the v3.33.0-rc2. The snapshots tab does not display anything. It only shows that it is loading, but nothing appears.

I have also attached the current diagnostic file. What I find particularly interesting is that it shows me an error in the env variable PBS_NODE_NAME, even though this is configured.

[pulse_diagnostics_2025-06-30T08-53-11.json](https://github.com/user-attachments/files/20976382/pulse_diagnostics_2025-06-30T08-53-11.json)

**Comment by rcourtman** [comment]
The snapshots tab shows VM/LXC snapshots (point-in-time snapshots stored on PVE nodes), not PBS backups. Your diagnostics show `pveBackups.guestSnapshots: 0`.

If you're expecting to see PBS backups (279 detected), those appear in the **Backups** tab, not Snapshots.

If you do have VM/LXC snapshots that should be showing:
1. Check the browser console (F12) for any errors
2. Try creating a test snapshot on any VM/container, then refresh Pulse
3. Restart Pulse service to force a fresh data collection

Note: The PBS_NODE_NAME requirement shown in your diagnostics is outdated - recent versions auto-discover this. I've updated the diagnostics tool to reflect this change.

**Comment by pluusla** [comment]
@rcourtman 

ah, now i understand. i almost suspected it, but wasn't quite sure. Then that works for me. The backup tab shows everything. Thank you for your patience! I'll wait for the stable release.

**Comment by rcourtman** [comment]
You won't be the only one confused by this change. In previous releases, having them combined caused significant issues and required numerous workarounds.

**Comment by Lynka7** [comment]
@rcourtman I didn't want to create a new issue so I had to comment here, what happened to beautiful GUI at the backup section ? Current Version 3.40.1 is just plain List. I don't think there was anything wrong with previous UI that had the calendar .....Any reason why you chose to change that ?

**Comment by rcourtman** [comment]
@Lynka7 Thanks for the feedback - I get that the change feels like a regression.

The short answer: those visual elements (summary cards, charts, calendar) were duplicating information already visible in the table. The current table sorted by recency actually shows everything you need at a glance - today's backups at the top, with clear patterns as you scroll.

I've been following a "less is more" approach with Pulse. Too many monitoring tools start pretty but become cluttered and slow to use. I'm trying to avoid that trap by keeping only what's essential.

**That said** - I do think the historical line chart was genuinely useful, and I'm planning to bring it back in the next version. The release notes for v3.40.0 mentioned this change, but I realize not everyone reads those in detail.

Quick question: What specifically do you miss? Is it:
- The visual appeal/polish?
- The calendar view for date navigation?
- The line chart trends?
- Something else?

This will help me prioritize what to reintroduce. I'm also making search the primary way to filter data (just type and watch it filter live) - have you tried that approach?

edit* One more thing - the less logic I apply to summarize/interpret data, the fewer issues I get from users seeing unexpected values. Raw data in a table is harder to misinterpret than calculated summaries.

**Comment by rcourtman** [comment]
Closing as stale. This issue is from 6+ months ago. PBS backup display has been reworked in v4. Please upgrade to v4.1.8 and reopen if you're still unable to view PBS backups.

**Comment by rcourtman** [comment]
Thanks for the report. Closing since triage-complete with no updates for 66 days.
