### ISSUE TITLE
[BUG] No pulse installation found when updating with community script

### ISSUE THREAD

**Issue by hsenechal** [rcourtman/Pulse#118]
When updating with command "update", or by calling the community script URL, i get an error saying "No Pulse Installation Found!"

![Image](https://github.com/user-attachments/assets/76517708-61ff-4918-b3d7-f5649ad2cfe7)

No change made to original installation folder in /opt/pulse-proxmox/

![Image](https://github.com/user-attachments/assets/fdde01b7-c16e-41a6-a9a8-e0b0c2104a9a)

**Comment by divemasterjm** [comment]
> When updating with command "update", or by calling the community script URL, i get an error saying "No Pulse Installation Found!"
> 
> ![Image](https://github.com/user-attachments/assets/76517708-61ff-4918-b3d7-f5649ad2cfe7)
> 
> No change made to original installation folder in /opt/pulse-proxmox/
> 
> ![Image](https://github.com/user-attachments/assets/fdde01b7-c16e-41a6-a9a8-e0b0c2104a9a)

same to me, the only thing is now de directory is in /opt/pulse instead on /opt/pulse-proxmox, i've tried update first on the settings page. i saw pulse permisions error, tried to update over the update command in proxmox lxc shell and got this error

**Comment by hsenechal** [comment]
Renaming the folder to /opt/pulse allow the update script to run, but get into a new error because the service is not named pulse.service but pulse-monitor.service

![Image](https://github.com/user-attachments/assets/60795b77-83ed-4cf1-92a9-b85134458f28)

![Image](https://github.com/user-attachments/assets/c9a4b51c-5a92-451a-9d28-4978bf49b000)

**Comment by hsenechal** [comment]
Found a manual fix :

1. systemctl stop pulse-monitor
2. mv /opt/pulse-proxmox/ /opt/pulse
3. Edit /etc/systemd/system/pulse-monitor.service to reflect the new path /opt/pulse
4. mv /etc/systemd/system/pulse-monitor.service /etc/systemd/system/pulse.service
5. systemctl daemon-reload
6. systemctl start pulse

Now you can run the update / community script

**Comment by rcourtman** [comment]
Fixed\! I've updated the installer script to properly handle the migration from old service names and paths.

**For existing users:** Backup your config first, then run either:
- The installer: `bash <(curl -s https://raw.githubusercontent.com/rcourtman/Pulse/main/scripts/install-pulse.sh)`
- Or the community script again

The script now properly detects old installations and migrates them to the new `/opt/pulse` location with `pulse.service`.

**Comment by eissens** [comment]
Okee, I did the installer script and it updated my installation... thx.

**Comment by zandhaas** [comment]
The update is still not working on my installation. 
When I follow the manual cp and mv command sequence Iit seems to work but in my GUI still version [3.11.1-dev.0 is shown and it still says version 4.14.0 is available for update.

As extra step I had to create the /etc/pulse  directory because the update proces said it could not find that directory.

**Comment by zandhaas** [comment]
Long story short. I removed the old Pulse LXC and installed a new one with the community script.
