### ISSUE TITLE
rcourtman/pulse:latest or rcourtman/pulse:v4.0.1 still on v4.0.0

### ISSUE THREAD

**Issue by raregtp** [rcourtman/Pulse#253]
Have reconfigured my docker-compose.yml, but with both of the mentioned tags when I get into the interface, it still shows v4.0.0, won't save settings, and doesn't show any resources from my cluster even though the connection tests OK when adding each of the three hosts.  Additionally, I see an "RC" tag at the top of the dashboard:

<img width="1299" height="533" alt="Image" src="https://github.com/user-attachments/assets/58a204d4-5c5d-4bb9-8afc-4a171944cce0" />

Seems like I'm still pulling down v4.0.0 when updating my stack.

**Comment by raregtp** [comment]
Just to add a bit more.....looking at the digests for the releases, it does indeed look like the latest tag (and 4.0.1 if you go look) and the v4 tag have the same digests.

<img width="1825" height="836" alt="Image" src="https://github.com/user-attachments/assets/ff5ece8b-09aa-4d12-9ac1-d9ace22bedc6" />

**Comment by rcourtman** [comment]
Fixed in v4.0.2 - the fallback version was hardcoded to 4.0.0, now correctly reports the actual version. Docker images have been rebuilt and pushed.

**Comment by raregtp** [comment]
Just tried this.....used the latest tag as well as the v4.0.2 tag.  Application now reports 4.0.1 version, but still cannot get my config to show any services.  Added one host from my Proxmox cluster, and it tests successfully, but nothing shows up for VMs or anything.  Also noticed nothing being saved in my mapped data folder except for an alerts folder with some json files in it.  I'm using docker swarm (see config)....including screenshots from the Pulse app...let me know if you need to see anything else:

<img width="1333" height="607" alt="Image" src="https://github.com/user-attachments/assets/60c82ae9-f027-4219-a91c-cca59daaac5c" />

<img width="1333" height="607" alt="Image" src="https://github.com/user-attachments/assets/040cf243-5086-4ecb-a7db-38525e6d2cbb" />

<img width="1312" height="974" alt="Image" src="https://github.com/user-attachments/assets/ce2213f5-6580-4a08-b795-3d0b663b35a0" />

<img width="644" height="418" alt="Image" src="https://github.com/user-attachments/assets/b16d5dd0-8099-4840-bc8f-2c9baa613f7c" />

**Comment by rcourtman** [comment]
hey @raregtp, found the issues you're experiencing. The Docker build was missing the VERSION file and the config persistence was using the wrong directory.

Just pushed fixes in v4.0.3-test if you want to try it out. The main issues were:
- VERSION file wasn't being copied into the Docker image (causing version display issues)
- Config was trying to save to /etc/pulse instead of /data (causing the persistence issues)

Should fix both the version display and the missing VMs/services problem. Let me know if it works for you\!

**Comment by rcourtman** [comment]
Update: I've tested the fixes locally and confirmed they work properly. The issues were:

1. VERSION file wasn't being copied to the final Docker image (only to build stage)
2. Config persistence was using hardcoded /etc/pulse instead of the PULSE_DATA_DIR environment variable

Both are now fixed and config persistence is working correctly in Docker. The v4.0.3-test tag should resolve all your issues.

**Comment by rcourtman** [comment]
v4.0.3 is now released with all the fixes. You can update your Docker deployment to `rcourtman/pulse:latest` or `rcourtman/pulse:v4.0.3`

The release includes both the Docker fixes and the binary artifacts for non-Docker installations.

**Comment by raregtp** [comment]
I'll see if I can give it a shot later tonight..... I don't expect to be in front of my system for most of the evening at this point.  If not tonight I'll let you know first thing in the morning.  Thanks for the quick fixes!

**Comment by raregtp** [comment]
Ok ..... Just tried it..... The version is correct now after I updated the stack.  But it's still not persisting data when I restart the stack.  I can configure one of my proxmox hosts and it shows connected successfully, but no VMs or backups or anything show up and if I stop and restart the stack the proxmox host I added is gone.

Thoughts?  Thanks!

**Comment by rcourtman** [comment]
@raregtp looking at your swarm config, the issue might be with how the volume is mounted. can you check a few things:

1. check what's actually in the data directory:
```bash
docker exec pulse ls -la /data
```

2. check the logs for any permission errors:
```bash
docker service logs pulse_pulse --tail 50
```

3. verify the env var is set:
```bash
docker exec pulse env | grep PULSE_DATA_DIR
```

also in your swarm config, try being explicit about the mount:
```yaml
volumes:
  - type: volume
    source: pulse_data
    target: /data
```

if you're still not seeing VMs after adding a node, check if the API token has the right permissions - needs Sys.Audit on / and VM.Audit on /vms

**Comment by rcourtman** [comment]
@raregtp v4.0.4 is released with fixes that might help your persistence issue. the main change is fixing path confusion between /etc/pulse and /var/lib/pulse

docker images are updated:
```bash
docker pull rcourtman/pulse:v4.0.4
```

if you're still having issues with swarm, try adding this to your compose file to ensure the data dir is set:
```yaml
environment:
  - PULSE_DATA_DIR=/data
```

let me know if persistence still isn't working after v4.0.4

**Comment by raregtp** [comment]
Ok....saw that you released 4.0.5, so tried that just now.  Doesn't seem to be any change for me.  Here's some answers to your questions:

Data directory:

<img width="936" height="113" alt="Image" src="https://github.com/user-attachments/assets/b3d4e20c-b674-4e2b-8f09-d76347949d6f" />

Container logs (and I suspect the ERR entries may help point us in the right direction....and I've share up to the point where they just start repeating the same ERR entry):

<img width="1170" height="954" alt="Image" src="https://github.com/user-attachments/assets/29b0e433-0eef-4401-9f0d-b821e50c77fc" />

Pulse data dir env:

<img width="1036" height="33" alt="Image" src="https://github.com/user-attachments/assets/12434299-fef0-45c9-900c-bd045e38dcd7" />

As far as being explicit about the mount, haven't done this as I have more than 20 stacks that have their volumes defined like I have in the stack config with no issues, and the fact that we are writing something seems to indicate it's not a volume issue.  I have also double-checked my  user and api token permissions....both my pulse user and api token for Proxmox have the PVEAuditor role, and I did double-check that role and it contains both Sys.Audit and VM.Audit on /, and is set to propagate.  This is the same user and api token that I was using with version 3.x.

I do have a question on 4.0.5, though....you shared the following docker run command in the release notes:

docker run -d --name pulse \
  -p 7655:7655 \
  -v pulse-data:/etc/pulse \
  rcourtman/pulse:latest

In that command, you have the pulse-data directory mapped to /etc/pulse.  Should I be changing from /data to /etc/pulse??

Let me know what other questions you have.  Prior to 4.x, 3.x was working great on my Proxmox cluster and with the user/api that I'm using, all with the same stack config.

Thanks!

**Comment by rcourtman** [comment]
@raregtp found the issue - there was a bug where config handlers were using the wrong directory path. Fixed in v4.0.6 just released.

the fix ensures config is saved to the mounted /data directory instead of /etc/pulse. pull the latest image:
```bash
docker pull rcourtman/pulse:v4.0.6
```

make sure your volume is mounted to /data:
```yaml
volumes:
  - pulse_data:/data
```

let me know if persistence works now

**Comment by raregtp** [comment]
Sounds good....waiting for it to hit Docker Hub and will try ASAP.

**Comment by raregtp** [comment]
Ok...just tried it out.  Confirmed the version now shows 4.0.6, but there doesn't seem to be any change at all from 4.0.5.  Logs still look the same (with the same errors about cluster health), contents of the data dir still look the same, and still acts the same in that when I stop the stack and restart it, my previously configured hosts are gone.  I did take the extra step to shut down the stack, clear out the data dir, and also removed all hanging docker images for the pulse stack.  Restarted the stack, but it didn't change anything.

Anything else I can look at to share and help figure this out??

**Comment by rcourtman** [comment]
@raregtp v4.0.6 is now on Docker Hub - amd64 is ready, arm builds still pushing. give it a try when you can

**Comment by raregtp** [comment]
I actually saw it hit about 30 minutes ago and already tried it.....see my previous post. :)

**Comment by rcourtman** [comment]
@raregtp thanks for testing. The fact that you're still seeing cluster health errors in the logs is concerning. Can you share:

1. The exact error messages from the logs
2. What files are being created in your /data directory 
3. Your docker-compose or swarm config

The fix in v4.0.6 should save configs to /data instead of /etc/pulse. If files are still going to the wrong place, there might be something else going on with the volume mount.

Can you exec into the container and check:
```bash
docker exec pulse ls -la /data
docker exec pulse ls -la /etc/pulse
docker exec pulse env | grep PULSE_DATA_DIR
```

**Comment by rcourtman** [comment]
@raregtp found the actual bug - v4.0.6 was still using the wrong persistence instance in some cases.

v4.0.7 is now available with the real fix:
```bash
docker pull rcourtman/pulse:v4.0.7
```

The handlers were calling a global SaveConfig() which used a persistence instance initialized at startup, potentially with the wrong path. Now they use their own correctly-initialized persistence instance.

Sorry for the confusion - this should actually work now.

**Comment by raregtp** [comment]
Just tried 4.0.7......not seeing any change, still not saving configs.  I'll gather the info from your previous post later this afternoon....stuck in meetings for the next couple of hours.

**Comment by raregtp** [comment]
Ok....here you are.

<img width="1043" height="337" alt="Image" src="https://github.com/user-attachments/assets/cfeef586-c6cd-4ace-9356-d5ccba3781a6" />

Here are the log files....look to the WRN and ERR lines for the errors I'm speaking of (obviously fake server and hidden IP have real info in my unsanitized config):

8:58PM INF Generated new encryption key
8:58PM DBG Config persistence initialized configDir=/data encryptionEnabled=true nodesFile=/data/nodes.enc systemFile=/data/system.json
8:58PM INF System settings loaded file=/data/system.json
8:58PM INF Loaded system configuration interval=5000
8:58PM INF Starting Pulse monitoring server
8:58PM INF Loaded alert history count=0
8:58PM INF Restored active alerts from disk restored=0 total=0
8:58PM INF Alert configuration updated
8:58PM INF Updated notification grouping options byGuest=false byNode=false
8:58PM INF Initializing PVE clients count=0
8:58PM INF Initializing PBS clients count=0
8:58PM INF Starting monitoring loop pollingInterval=5000
8:58PM INF Server listening host=0.0.0.0 port=7655
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0

9PM INF WebSocket upgrade request host=pulse.myacs.com origin=https://pulse.myacs.com userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
8:59PM INF WebSocket client created client=client-1754513948360332544
8:59PM INF ReadPump started client=client-1754513948360332544
8:59PM INF WebSocket client connected client=client-1754513948360332544
8:59PM INF WritePump started client=client-1754513948360332544
8:59PM INF Sending welcome message client=client-1754513948360332544
8:59PM INF Welcome message sent client=client-1754513948360332544
8:59PM INF Sending initial state to client client=client-1754513948360332544 dataKB=0 dataLen=575
8:59PM INF Initial state sent successfully client=client-1754513948360332544
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Test connection request received hasTokenValue=true host=https://fakeserver.myacs.com:8006 name=fakeserver tokenName=pulse@pve!pulse type=pve user=
8:59PM INF Parsed authentication details parsedTokenName=pulse parsedUser=pulse@pve
8:59PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
8:59PM INF Saved active alerts to disk count=0
9:00PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
9:00PM INF Add node request received hasTokenValue=true host=https://fakeserver.myacs.com:8006 name=fakeserver tokenName=pulse@pve!pulse type=pve user=
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Got cluster nodes cluster_nodes=3
9:00PM INF Detected Proxmox cluster, auto-discovering all nodes name=fakeserver nodes=3
9:00PM INF Added Proxmox cluster with auto-discovered endpoints cluster=fakeserver endpoints=3
9:00PM INF Nodes configuration saved encrypted=true file=/data/nodes.enc pbs=0 pve=1
9:00PM INF Reloading monitor configuration
9:00PM INF Nodes configuration loaded encrypted=true file=/data/nodes.enc pbs=0 pve=1
9:00PM INF Loaded nodes configuration pbs=0 pve=1
9:00PM INF System settings loaded file=/data/system.json
9:00PM INF Loaded system configuration interval=5000
9:00PM INF Monitoring loop stopped
9:00PM INF Loaded alert history count=0
9:00PM INF Restored active alerts from disk restored=0 total=0
9:00PM INF Alert configuration updated
9:00PM INF Updated notification grouping options byGuest=false byNode=false
9:00PM INF Initializing PVE clients count=1
9:00PM INF Configuring PVE instance hasToken=true host=https://fakeserver.myacs.com:8006 name=fakeserver user=
9:00PM INF Creating cluster-aware client cluster=fakeserver endpoints=["https://hiddenip:8006","https://hiddenip:8006","https://hiddenip:8006"]
9:00PM INF Cluster client created successfully cluster=fakeserver endpoints=3 instance=fakeserver
9:00PM INF Initializing PBS clients count=0
9:00PM INF Monitor reloaded successfully
9:00PM INF Starting monitoring loop pollingInterval=5000
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM WRN Marking cluster node as unhealthy cluster=fakeserver endpoint=https://hiddenip:8006
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM WRN Marking cluster node as unhealthy cluster=fakeserver endpoint=https://hiddenip:8006
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM WRN Marking cluster node as unhealthy cluster=fakeserver endpoint=https://hiddenip:8006
9:00PM ERR Failed to get nodes error="poll_nodes failed on fakeserver: all cluster nodes failed for fakeserver" instance=fakeserver
9:00PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM ERR Failed to get nodes error="poll_nodes failed on fakeserver: no healthy nodes available in cluster fakeserver" instance=fakeserver
9:00PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM ERR Failed to get nodes error="poll_nodes failed on fakeserver: no healthy nodes available in cluster fakeserver" instance=fakeserver
9:00PM INF Broadcasting state update (ticker) containers=0 nodes=0 pbsBackups=0 vms=0
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse@pve!pulse realm=pve tokenName=pulse user=pulse
9:00PM ERR Failed to get nodes error="poll_nodes failed on fakeserver: no healthy nodes available in cluster fakeserver" instance=fakeserver

And finally my swarm stack config:

<img width="594" height="442" alt="Image" src="https://github.com/user-attachments/assets/b98c228c-de97-4ef6-8b8d-862d6d49147d" />

**Comment by raregtp** [comment]
Let me know what else you need.  Thanks!

**Comment by raregtp** [comment]
#257 

Exactly what I'm seeing.....and that's showing up in the logs also.

**Comment by kinggerrard** [comment]
Pulse | Version: [4.0.10](https://github.com/rcourtman/Pulse/releases) - Docker

So i've been following along and testing it out too, I tried mounting to this:

    environment:
      - PULSE_DATA_DIR=/etc/pulse
    volumes:
      - /home/richay/docker/pulse:/etc/pulse

Data persists this way, but fails when I just place it in /data

**Comment by raregtp** [comment]
Tried 4.0.10.....data still not persisting, and I'm still getting the following error in the logs over and over:

ERR Failed to get nodes error="poll_nodes failed on fakeserver: no healthy nodes available in cluster fakeserver" instance=fakeserver

I've deleted my stack, all data in the "data" directory, and removed the image......same results.  I've also tried what @kinggerrard described above with no change, and I've changed container data permissions back to root.....but nothing seems to change the behavior at all.

**Comment by raregtp** [comment]
@rcourtman is there any other logging or details I can provide to help on this issue??

**Comment by Christoph-Wagner** [comment]
See here: https://github.com/rcourtman/Pulse/issues/257#issuecomment-3168963348

Try disabling SSL verification, apparently pulse connects via IP even if you use a domain.
