### ISSUE TITLE
4.1.0 - Notification Settings are not being saved and not working

### ISSUE THREAD

**Issue by spydisec** [rcourtman/Pulse#277]
After saving the notification settings, testing them does not work. Additionally, when I refresh the page, the settings I saved are gone. This means notification settings are not being saved in version 4.1.0. I’m using a dedicated LXC on PVE.

<img width="1277" height="343" alt="Image" src="https://github.com/user-attachments/assets/633c13e6-b557-4f40-80af-e933ebb80452" />

<img width="446" height="160" alt="Image" src="https://github.com/user-attachments/assets/2cd13e4c-1ed0-40ff-8e72-3bb259fa564e" />

**Comment by rcourtman** [comment]
try updating to v4.1.1 - there were some persistence fixes. if that doesn't work, check that the pulse service has write permissions to /etc/pulse:
ls -la /etc/pulse/

should be owned by the pulse user. if not:
chown -R pulse:pulse /etc/pulse
systemctl restart pulse

also try clearing your browser cache or testing in an incognito window in case it's a frontend caching issue.

i'm also looking into some permission issues with LXCs - been having an absolute nightmare getting updates to work properly in containers, so there might be something weird going on there.

**Comment by rcourtman** [comment]
notification settings persistence fixed in v4.1.x

**Comment by rcourtman** [comment]
Closing as fixed - notification saving issues resolved in v4.1.8.

**Comment by spydisec** [comment]
Hi @rcourtman , Still not working, even though I updated to the latest version 4.1.8. Please find the below image for your reference:

<img width="1261" height="954" alt="Image" src="https://github.com/user-attachments/assets/4f694f39-a4e2-4e2c-8e9c-94e32eb82354" />
