### ISSUE TITLE
Installed fresh 4.1.3 show 4.1.1

### ISSUE THREAD

**Issue by wisepds** [rcourtman/Pulse#282]
We are working at same time jejejeje...

I have fresh installed 4.1.3 from your file

Now, ram in some VM show well, but my pfsense that are almost on 100% show 0%

<img width="582" height="104" alt="Image" src="https://github.com/user-attachments/assets/3e0bdf69-5235-4fb3-ac65-731d50b90dc3" />

<img width="388" height="231" alt="Image" src="https://github.com/user-attachments/assets/f1640550-bfe9-4a2f-b418-ef7f35e53385" />

https://github.com/rcourtman/Pulse/releases/download/v4.1.3/pulse-v4.1.3-linux-amd64.tar.gz

and pulse show 4.1.1 

<img width="798" height="617" alt="Image" src="https://github.com/user-attachments/assets/c3e43334-7268-4ae2-9902-2a3a9ebd621e" />

<img width="982" height="402" alt="Image" src="https://github.com/user-attachments/assets/9613f52c-c4e5-4574-90bd-186161c5a952" />

**Comment by rcourtman** [comment]
the version showing 4.1.1 when you installed 4.1.3 is likely a caching issue. try clearing your browser cache or hard refresh (Ctrl+F5).

for the pfSense RAM showing 0% - this might be because pfSense doesn't have the qemu guest agent installed. without the guest agent, Proxmox can't get accurate memory usage from inside the VM.

to fix the RAM display:
1. install qemu guest agent in pfSense if possible
2. or just monitor it from pfSense's own dashboard

try v4.1.5 which just released - it has some additional fixes.

**Comment by rcourtman** [comment]
version display fixed in v4.1.6

**Comment by wisepds** [comment]
Hi, Qemu agent it's working fine on my pfsense:

<img width="866" height="278" alt="Image" src="https://github.com/user-attachments/assets/98c837e9-2678-4541-aea0-d3a860f547c3" />

Still shows 0%

**Comment by rcourtman** [comment]
Closing - this was a browser cache issue. Clear cache (Ctrl+F5) to see correct version.
