### ISSUE TITLE
Pulse Releases -  All In One Binaries File pulse.VERSION.tar.gz - v4.1.2 and now the Latest v4.1.3 - Missing Binaries, Hidden Files and Folders

### ISSUE THREAD

**Issue by kenrmayfield** [rcourtman/Pulse#284]
@rcourtman 

All In One Binaries File **pulse.VERSION.tar.gz**  missing Binaries, Hidden Files and Folders .

**Can you go back and Repackaged All the Binaries in One like Other Versions?**

This starts at v4.1.2  and now the Latest v4.1.3.

**Here is v4.1.3 Extracted:**

<img width="625" height="154" alt="Image" src="https://github.com/user-attachments/assets/bf244851-6576-40b6-88ab-6df74a527d33" />

**Example of All Binaries Included in **pulse.VERSION.tar.gz** for Version v4.1.0-rc.6 and Previous Versions :**
Here is **v4.1.0-rc.6** All in One Binaries File **pulse-v4.1.0-rc.6.tar.gz** showing All the Binaries.

Extracted Contents:

<img width="624" height="280" alt="Image" src="https://github.com/user-attachments/assets/1bc3b783-7ada-48c3-9287-4fc0c2be2462" />

**Comment by rcourtman** [comment]
you're absolutely right - the universal tarball is missing the frontend files. this was my mistake in the build script. i'll fix it now and re-upload the correct archives for v4.1.2 and v4.1.3.

the architecture-specific tarballs (pulse-v4.1.3-linux-amd64.tar.gz etc) do have everything, but the universal one is broken. fixing now.

**Comment by rcourtman** [comment]
fixed\! i've re-uploaded the universal tarballs for v4.1.2 and v4.1.3. they now contain all binaries (pulse-linux-amd64, pulse-linux-arm64, pulse-linux-armv7) plus the frontend-modern directory.

thanks for catching this - the build script was creating them wrong.

**Comment by kenrmayfield** [comment]
@rcourtman 


Hey.......sorry........but the the **pulse.VERSION.tar.g File** is still not Packaged Correctly.

It is still missing Binaries, Hidden Files and Folders.

**v4.1.4 is showing when Extracted:**

<img width="625" height="154" alt="Image" src="https://github.com/user-attachments/assets/db475932-0bc9-438f-bda4-54de77768c58" />

**It should be showing:**

<img width="624" height="280" alt="Image" src="https://github.com/user-attachments/assets/9d7a0b25-4603-4280-b8cf-5367e91fa94f" />

**Comment by kenrmayfield** [comment]
@rcourtman

Same Thing............................ 

**v4.1.5(pulse.v4.1.5.tar.gz) is showing when Extracted:**


<img width="625" height="154" alt="Image" src="https://github.com/user-attachments/assets/c53a7998-9ef5-459f-bb70-822b19e71d03" />

**Comment by kenrmayfield** [comment]
@rcourtman 

Sorry but the Issue Persist with Newer Versions Past v4.1.3.

Creating a New Issue since this Issue was Closed.

Created New Issue: https://github.com/rcourtman/Pulse/issues/288#:~:text=Files%20and%20Folders-,%23288,-Edit
