### ISSUE TITLE
Notification Services Not Working

### ISSUE THREAD

**Issue by pluusla** [rcourtman/Pulse#305]
**Description**
I am unable to get the notification services working in Pulse. Specifically, I tested the Telegram notification integration, but messages are not sent and I always receive an HTTP 404 error in the logs.

Pulse version 4.3 (same behavior in the previous versions)

**Steps to Reproduce**
Set up notification service with the following endpoint (token and chat_id are redacted for privacy):

```
https://api.telegram.org/bot111:222/sendMessage?chat_id=1111111
Trigger a test notification through Pulse.
```

**Expected Behavior**
A message should be sent to the specified Telegram chat.

**Actual Behavior**
No message is sent. In the logs, I only see an HTTP 400 status in the logs.

**Additional Information**
Token and chat_id are correct and manually tested.

The same API call works outside of Pulse (e.g., via browser or curl).

Logs
`Aug 12 15:20:55 pulse pulse[3158]: 3:20PM WRN Webhook returned non-success status status=400 type=alert-test-alert webhook=Telegram`

**additional question:**
Is it possible to send notifications using a self-hosted instance of the Apprise API with Pulse? I could not find anything about this in the documentation.

**Comment by rcourtman** [comment]
hey @pluusla, i think i found the issue

for telegram webhooks in pulse, the url should be:
```
https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage
```

without the `?chat_id=` parameter in the url. pulse needs the chat_id to be configured differently - either:

1. use a custom webhook with the full json template including your chat_id
2. or wait for a fix where we properly handle telegram chat_id configuration

the 400 error is likely because telegram is receiving the chat_id both in the url (which it doesn't expect) and in the json body

for now, try setting up a custom webhook with:
- url: `https://api.telegram.org/bot<YOUR_TOKEN>/sendMessage`
- method: POST
- payload template:
```json
{
  "chat_id": "YOUR_CHAT_ID",
  "text": "Pulse Alert: {{.Level}} - {{.Message}}",
  "parse_mode": "Markdown"
}
```

regarding apprise - pulse doesn't have native apprise support, but you can use the generic webhook feature to send to your apprise api endpoint with a custom payload format

**Comment by pluusla** [comment]
@rcourtman 

Maybe I'm too stupid, but I can't see anywhere in the notification tab for generic webhooks where I can store my own payload template. Or where exactly is this explained?

**Comment by rcourtman** [comment]
hey @pluusla, you're absolutely right, the ui doesn't have a field for custom payloads yet

good news though - just fixed the telegram issue. in the next release, telegram webhooks will work properly even with chat_id in the url. pulse will automatically extract it and put it in the json body where telegram expects it

for now with telegram:
1. select "Telegram Bot" as the service type when adding a webhook
2. use the url format: `https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage?chat_id=<YOUR_CHAT_ID>`
3. pulse will handle the rest

this fix will be in the next release. the custom payload template feature is something we should add to the ui in the future

**Comment by pluusla** [comment]
@rcourtman 

there is no service type telegram when adding a webhook:


<img width="1254" height="601" alt="Image" src="https://github.com/user-attachments/assets/7c870159-7096-408c-9d78-98282e9b3aa9" />

And yes, it would be great to be able to customize the payload template itself in the GUI. Then I could use the Apprise API.

**Comment by rcourtman** [comment]
hey @pluusla, just pushed a fix for both issues you raised

the telegram webhook problem is now fixed - pulse will automatically handle the chat_id parameter correctly even if you put it in the URL like the telegram docs suggest

also added custom payload templates for generic webhooks. when you select 'Generic' as the service type, you'll see a new 'Custom Payload Template' field where you can define any JSON format you need

the fix is in the main branch now and will be in the next release. thanks for reporting this and pointing out the missing custom payload feature

**Comment by rcourtman** [comment]
hey @pluusla, just released v4.3.1-rc.1 with the telegram fix and custom payload templates you suggested. would be great if you could test it out and let me know if it works for you

docker pull rcourtman/pulse:v4.3.1-rc.1

**Comment by pluusla** [comment]
@rcourtman 

Tested with rc1

Telegram is still not displayed as a service

It doesn't work with payload either and URL https://api.telegram.org/bot<YOUR_TOKEN>/sendMessage

So it doesn't seem to really work. The log remains the same as initially reported.

**Comment by rcourtman** [comment]
update: telegram will show up in the dropdown in the next release

**Comment by pluusla** [comment]
@rcourtman 

Even with version 4.3.5, neither Telegram nor Apprise work with a corresponding JSON body.

Somehow, all changes seem to have no effect (except that Telegram is now selectable, but does not work).

The log still shows the same thing. The URLs are correct and work via the curl command outside of Pulse.

**Comment by rcourtman** [comment]
hey @pluusla, added extensive debug logging in the latest commit to diagnose the Telegram issue. 

the code SHOULD be working - it extracts chat_id from the URL and adds it to the JSON payload. but clearly something's not right if you're getting 400 errors.

can you try this to help debug:
1. update to the latest main branch
2. set your log level to debug (LOG_LEVEL=debug)
3. try sending a test notification
4. check logs for lines containing "Telegram" - you should see what payload is being sent

in the meantime, if you need notifications working NOW, try using a generic webhook with a custom template:
- service: Generic
- url: https://api.telegram.org/bot<YOUR_TOKEN>/sendMessage
- add a custom payload template:
```json
{
  "chat_id": "YOUR_CHAT_ID",
  "text": "Pulse Alert: {{.Level}} - {{.Message}}",
  "parse_mode": "Markdown"
}
```

this bypasses the telegram-specific logic and just sends exactly what you specify

**Comment by pluusla** [comment]
@rcourtman 
And where can I find the .env file? I can't seem to find it anywhere. Pulse was installed via community script.

Otherwise: As already mentioned, I tried the workaround, but it doesn't work either.

Addition:

I read the instructions at https://github.com/rcourtman/Pulse/blob/main/docs/CONFIGURATION.md.
I didn't have a .env file -> I have now created one.
```
user@pulse:/# sudo systemctl restart pulse-backend`

Failed to restart pulse-backend.service: Unit pulse-backend.service not found. 
```

**Comment by pluusla** [comment]
> [@rcourtman](https://github.com/rcourtman) And where can I find the .env file? I can't seem to find it anywhere. Pulse was installed via community script.
> 
> Otherwise: As already mentioned, I tried the workaround, but it doesn't work either.
> 
> Addition:
> 
> I read the instructions at https://github.com/rcourtman/Pulse/blob/main/docs/CONFIGURATION.md. I didn't have a .env file -> I have now created one.
> 
> ```
> user@pulse:/# sudo systemctl restart pulse-backend`
> 
> Failed to restart pulse-backend.service: Unit pulse-backend.service not found. 
> ```
I was able to enable debug logging. But even so, you can't see much more here.
I also have the feeling that it only triggers a single webhook during the test, even though I run or test all three. 

```
Aug 15 13:51:09 pulse pulse[2112]: 1:51PM DBG Request handled duration=0.019626 method=GET path=/api/notifications/webhooks
Aug 15 13:51:09 pulse pulse[2112]: 1:51PM DBG Request handled duration=0.29579 method=GET path=/api/notifications/webhook-templates
Aug 15 13:51:11 pulse pulse[2112]: 1:51PM WRN Webhook returned non-success status status=400 type=alert-test-alert webhook=test
Aug 15 13:51:11 pulse pulse[2112]: 1:51PM WRN Webhook returned non-success status status=400 type=alert-test-alert webhook=test
Aug 15 13:51:12 pulse pulse[2112]: 1:51PM WRN Webhook returned non-success status status=400 type=alert-test-alert webhook=test
```

**Comment by rcourtman** [comment]
hey @pluusla, telegram notifications got a major fix in v4.4.0 that should resolve the 400 errors you're seeing. the webhook formatting and grouped alerts handling was completely reworked.

can you update to v4.4.0 and let me know if it works now? if you're still having issues after updating, i'll dig deeper into your specific setup.

regarding apprise api - not currently supported but it's an interesting idea for future integration

**Comment by pluusla** [comment]
@rcourtman 
Thanks for letting me know. I've already tested this. Telegram still isn't working. But the custom webhook with body and my Apprise URL is now working! This is a step forward.

**Comment by pluusla** [comment]
@rcourtman 
The problem with Telegram not working still persists in version 4.5.1.
Interesting observation: I have stored 3 webhooks. The first is a custom webhook on my apprise api installation, the second on api.telegram. When I click on test for the second webhook, the first webhook is triggered (apprise is now working). It seems that the iteration or something is not correct here.

**Comment by rcourtman** [comment]
hey @pluusla, telegram is definitely working in the latest version. here's what a working telegram webhook config looks like:

1. URL format: `https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage`
2. Method: POST
3. Headers: Content-Type: application/json
4. Template should be a JSON payload like:
```json
{
  "chat_id": "YOUR_CHAT_ID",
  "text": "{{.Message}} on {{.Node}}",
  "parse_mode": "Markdown"
}
```

make sure you're using your actual bot token (from BotFather) and chat ID. you can get your chat ID by messaging your bot and then visiting `https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates`

if it's still not working, check the pulse logs with debug logging enabled to see the exact request being sent

**Comment by pluusla** [comment]
@rcourtman It doesn't work, and the URL is correct. It works via curl. As I said, please refer to my previous comment. There is something fundamentally wrong with the webhooks if a different webhook is triggered during testing than the one selected. I have also already posted the debug logs.

Addition:
When I disable my custom apprise webhook and only change the name in the Telegram webhook, it works. However, when I reactivate the apprise webhook and click on "Test," the Telegram webhook is triggered instead of the Apprise webhook. If I then change something in the Apprise webhook again and click on test there, Telegram no longer works.

It almost seems as if only one webhook is active at a time and it chooses which one is triggered rather arbitrarily.

As mentioned, I think there is something fundamentally wrong with the triggering of the webhooks.

**Comment by rcourtman** [comment]
hey @pluusla, found the test button bug - webhookId wasn't being passed to backend when clicking test. just fixed it. i've been referring to actual telegram alerts working (which they do for me and other users), but wasn't focusing on the test button specifically which was indeed broken. fix will be in next release

**Comment by pluusla** [comment]
@rcourtman 
Great, now it works perfectly! Thank you for your patience!

**Comment by rschoell** [comment]
I can also confirm it's working. Can you please fix the webhooks.md file which currently does not have the correct info? Thanks for your great tool.
