### ISSUE TITLE
Using Pusle with Reverse Proxy failes in Connection Issue

### ISSUE THREAD

**Issue by timscha** [rcourtman/Pulse#333]
Since my upgrade from 4.3 to 4.4 and now even to 4.5, I am facing connection issues when opening pulse via reverse proxy. When I open Pulse directly with the port it works.

If I open it via the domain I am receiving a Connection Lost - Unable to connect to the backend server. Attempting to reconnect.. message.

Diagnostics says WebSocket Status: Disconnected

The thing is, I am using the provided Apache vhost config from the docs:

```
<VirtualHost *:443>
    ServerName pulse.mydomain.tld

    SSLEngine on
        SSLCertificateFile      /root/.acme.sh/pulse.mydomain.tld/fullchain.cer
        SSLCertificateKeyFile   /root/.acme.sh/pulse.mydomain.tld/pulse.mydomain.tld.key

    # Enable necessary modules:
    # a2enmod proxy proxy_http proxy_wstunnel headers

    # WebSocket proxy
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:7655/$1" [P,L]

    # Regular HTTP proxy
    ProxyPass / http://localhost:7655/
    ProxyPassReverse / http://localhost:7655/

    # Preserve host headers
    ProxyPreserveHost On

    # Forward real IP
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "https"

    # Disable buffering
    ProxyIOBufferSize 65536
</VirtualHost>
```

I already tried a reinstallation.

**Comment by rcourtman** [comment]
hey @timscha, found the issue. in v4.4 we tightened websocket security but didn't properly handle reverse proxy headers.

fixed it to respect X-Forwarded-Proto and X-Forwarded-Host headers from your apache proxy. will be in the next release.

as an immediate fix, you can set ALLOWED_ORIGINS=https://pulse.mydomain.tld in your environment, but you won't need that after updating to the next release.

**Comment by timscha** [comment]
Thanks for the fast response @rcourtman - I can confirm with the variable being set it is working again. Thanks!

**Comment by timscha** [comment]
Btw I found another bug. That button to generate the config is not working when adding Proxmox new. @rcourtman 

<img width="1330" height="1848" alt="Image" src="https://github.com/user-attachments/assets/ec7d54b7-759b-405d-9c07-49b4bf325e66" />

**Comment by forke24x7** [comment]
> hey [@timscha](https://github.com/timscha), found the issue. in v4.4 we tightened websocket security but didn't properly handle reverse proxy headers.
> 
> fixed it to respect X-Forwarded-Proto and X-Forwarded-Host headers from your apache proxy. will be in the next release.
> 
> as an immediate fix, you can set ALLOWED_ORIGINS=https://pulse.mydomain.tld in your environment, but you won't need that after updating to the next release.

Is this fixed in 4.5.1? I have the exact same issue (using Pangolin) in Pulse 4.5.1. with CORS Allowed Origins = *
If I change * to https://pulse.mydomain.de it works fine through Pangolin.

**Comment by rcourtman** [comment]
hey @forke24x7, the proxy header support (X-Forwarded-Proto/Host) is in v4.5.1, but seems there's still an issue with wildcard origins

can you check your pulse logs when the connection fails? should see a warning like "WebSocket connection rejected due to CORS" that shows what origin it's seeing

also, what headers does pangolin send? specifically looking for Origin, X-Forwarded-Proto, and X-Forwarded-Host headers

if you can share those details it'll help me fix this properly

**Comment by forke24x7** [comment]
After changing it back to * it still works - even from a different PC in another network. Can't reproduce unless I restore a backup. As I'm not familiar with this stuff I better keep it running as it works right now, maybe someone with more experience can dig into it.

**Comment by rcourtman** [comment]
thanks for the update @forke24x7

sounds like a settings refresh issue. for anyone else hitting this with reverse proxies:

**workaround**: if ALLOWED_ORIGINS=* isn't working:
1. change it to your specific domain (e.g., https://pulse.yourdomain.com)
2. save and wait for it to apply
3. change it back to * if you want wildcard
4. restart the pulse service to be safe

this seems to properly refresh the websocket origin checks. will look into making the settings updates more reliable in a future release

**Comment by rcourtman** [comment]
I am closing this because there has been no activity for several weeks and the workaround appears to have resolved the reverse proxy connection issue. Please reopen if this is still relevant.
