### ISSUE TITLE
Acknowledge alert button does not work

### ISSUE THREAD

**Issue by skibbipl** [rcourtman/Pulse#380]
After clicking acknowledge button, popup appears  but the acknowledge count stays 0.
<img width="1200" height="559" alt="Image" src="https://github.com/user-attachments/assets/092456d7-3735-4696-8d79-fa3c2d92bba4" />

**Comment by rcourtman** [comment]
@skibbipl should be fixed now. the acknowledge count wasn't updating due to a reactivity issue with how the store was being accessed in solidjs

can you test when you get a chance?

**Comment by skibbipl** [comment]
Are you talking about 4.10.0? If yes, them acknowledge works for 2 seconds and then again it's cleared. Full page refresh displays acknowledged alerts thou. So the issue is still there...
Also clearing and re acknowledging alert ends with error.
The whole alert page seems really buggy atm.

**Comment by blakestock** [comment]
I've got a similar issue on a freshly installed 4.11.0 where when I try to acknowledge an alert I get a message "Failed to acknowledge alert".  When looking at the console and clicking the button, I get a 404 Not Found message

<img width="1400" height="647" alt="Image" src="https://github.com/user-attachments/assets/5f667cd8-bbb7-48f2-9788-61c8f3fb0b22" />

**Comment by rcourtman** [comment]
can you try v4.13.0? improved alert acknowledgment synchronization: https://github.com/rcourtman/Pulse/releases/tag/v4.13.0

**Comment by NightHawkATL** [comment]
> can you try v4.13.0? improved alert acknowledgment synchronization: https://github.com/rcourtman/Pulse/releases/tag/v4.13.0

I just tried with v4.13.0 and I can report that I still get the "Failed to acknowledge" error in the top right corner.

<img width="1737" height="843" alt="Image" src="https://github.com/user-attachments/assets/9b78a91c-47bf-4283-8134-9c3fe31cd0c8" />

**Comment by blakestock** [comment]
> can you try v4.13.0? improved alert acknowledgment synchronization: https://github.com/rcourtman/Pulse/releases/tag/v4.13.0

Works great!  Cleaner UI/UX too!

<img width="1015" height="579" alt="Image" src="https://github.com/user-attachments/assets/5de4360f-d63d-45b7-acae-f4581adb7ce9" />

No issues anymore with alerts for me on v4.13.0

**Comment by skibbipl** [comment]
Yes, the new acknowledge mode works a lot better. How long notification is hidden? Previously it was restored after some time. Also I'm ready to close this issue, but I can see that @NightHawkATL still has some issues, so let's wait for more updates.

**Comment by rcourtman** [comment]
could you test v4.14.0-rc.1 and see if this is fixed

**Comment by NightHawkATL** [comment]
> could you test v4.14.0-rc.1 and see if this is fixed

This is fixed in rc.1 & rc.2
