### ISSUE TITLE
Cannot install on systems with multiple storage options

### ISSUE THREAD

**Issue by NightHawkATL** [rcourtman/Pulse#381]
I have multiple nodes with 2 drives (1 SSD & 1 NVME) and when trying to deploy Pulse on the one with the lowest resource use, I keep getting an error that it can't find the debian template in "PVE-DATA" (which is where I only store VM/LXC disks) but I have the template downloaded in my "ISOs" share so that all nodes will have access to the downloaded ISOs and CT templates.

<img width="353" height="310" alt="Image" src="https://github.com/user-attachments/assets/543e6009-853a-4282-9799-c631f47e6a7a" />

<img width="815" height="319" alt="Image" src="https://github.com/user-attachments/assets/51d2200f-1626-4769-8dd5-fb3333e6aba4" />

I think there should be 1 more step to ask where to look for the template rather than always assuming that there is only 1 storage device.

This is the error I am seeing.

<img width="961" height="619" alt="Image" src="https://github.com/user-attachments/assets/7f17f617-fcde-4011-b8dc-4e76b8defc26" />

**Comment by rcourtman** [comment]
hey @NightHawkATL, thanks for the detailed report. You're right that the installer was only checking the container storage for templates instead of all available template storages. Fixed in the latest commit - the installer now:

- Detects all storages that can contain templates (not just the container storage)
- Lists templates from all available storages in advanced mode
- Automatically selects the storage with most free space when downloading templates

This should work with your setup where templates are in the ISOs storage. Will be in the next release.

**Comment by NightHawkATL** [comment]
> hey [@NightHawkATL](https://github.com/NightHawkATL), thanks for the detailed report. You're right that the installer was only checking the container storage for templates instead of all available template storages. Fixed in the latest commit - the installer now:
> 
>     * Detects all storages that can contain templates (not just the container storage)
> 
>     * Lists templates from all available storages in advanced mode
> 
>     * Automatically selects the storage with most free space when downloading templates
> 
> 
> This should work with your setup where templates are in the ISOs storage. Will be in the next release.

Still appears to be doing a similar thing.

<img width="1502" height="588" alt="Image" src="https://github.com/user-attachments/assets/70b4a5ed-2aa5-4683-a54b-3e0d84f4c355" />

**Comment by rcourtman** [comment]
hey @NightHawkATL, good timing - just fixed the installation script to better handle multiple storage options. the script now:

- shows all available storage pools with their free space
- lets you pick which storage to use with numbered options
- properly detects templates across all storage locations
- downloads templates to the best storage if needed

you can test the updated script:
```bash
curl -sSL https://raw.githubusercontent.com/rcourtman/Pulse/main/install.sh | bash
```

it should now find your templates in the ISOs share and let you choose which storage to use for the container. let me know if it works better for you

**Comment by NightHawkATL** [comment]
Still doing the same:

<img width="1499" height="589" alt="Image" src="https://github.com/user-attachments/assets/1a50ed3a-aa11-4e2a-808e-8ce36b73cd11" />

**Comment by rcourtman** [comment]
hey @NightHawkATL , thanks for the report. just pushed a fix for this - can you test the updated install script and let me know if it works for you now?

**Comment by NightHawkATL** [comment]
Same thing. now, it looks like it is trying to download to "ISOs" but it is already there so it is error-ing out.

<img width="1507" height="547" alt="Image" src="https://github.com/user-attachments/assets/41dc6b58-28d3-43ad-b4e0-82683f0a5a67" />

**Comment by rcourtman** [comment]
looks like you're still using the old version - make sure to download the fresh install script:

```bash
wget -qO- https://raw.githubusercontent.com/rcourtman/Pulse/main/install.sh | bash
```

or if you saved it locally, re-download it first before running

**Comment by NightHawkATL** [comment]
ok, now I got this far and it seems to be hung..

<img width="684" height="617" alt="Image" src="https://github.com/user-attachments/assets/a57287f8-c389-4255-a9bd-6f3ada2b7826" />

**Comment by rcourtman** [comment]
the container created successfully but seems to be having network issues. can you check a few things while it's hanging:

1. in another terminal, run: `pct list` to see if the container was created
2. if it shows up, try: `pct enter <container-id>` and then `ip a` to see if it got an IP
3. or try: `pct exec <container-id> -- ip a`

the script waits 60 seconds for network to come up, so it might eventually timeout with an error message. let me know what you find

**Comment by NightHawkATL** [comment]
It works on DHCP, it probably didn't like the comma with no space between the dns servers. 

<img width="1066" height="513" alt="Image" src="https://github.com/user-attachments/assets/0c9b96db-c408-4d39-88df-a107bcfa0588" />

**Comment by rcourtman** [comment]
updated the script to make the DNS entry clearer - it now asks for space-separated DNS servers which is what Proxmox expects. should prevent that network hang issue.

feel free to close this if everything's working for you now

**Comment by NightHawkATL** [comment]
sure! Works as expected now.
