### ISSUE TITLE
No healthy nodes available in cluster

### ISSUE THREAD

**Issue by PlayrTBH** [rcourtman/Pulse#405]
<img width="1639" height="758" alt="Image" src="https://github.com/user-attachments/assets/87a7f5e7-44fb-40dd-84ce-fb66639a3385" />

Pulse shows no VM's but appears to see the nodes fine, here's what shows in docker logs:

6:42PM INF Starting parallel storage polling instance=pve.local onlineNodes=3 totalNodes=3
6:42PM WRN Failed to get node storage error="no healthy nodes available in cluster pve.local" node=pve1
6:42PM WRN Failed to get node storage error="no healthy nodes available in cluster pve.local" node=pve2
6:42PM WRN Failed to get node storage error="no healthy nodes available in cluster pve.local" node=pve
6:42PM INF Parallel storage polling completed duration=0.085904 failedNodes=3 instance=pve.local successfulNodes=0 totalStorage=0
6:42PM INF Syncing recently resolved alerts count=1

Unsure exactly why, no ideas as to what is causing pulse to think there's no healthy nodes.

**Comment by laurentpellet** [comment]
Pulse can connect to the cluster, but can't get the storage config.
It can poll VM but no storage nor backup.
Alerts are OK though

```
8:05PM INF Checking guest thresholds cpu=2.76803847965038 disk=-1 guest=TAHIA memory=56.581687927246094 thresholds=
8:05PM INF VMs and containers polled efficiently with cluster/resources containers=8 instance=Cluster vms=49
8:05PM WRN Failed to get cluster storage config - will continue with node storage only error="no healthy nodes available in cluster Cluster" instance=Cluster
8:05PM INF Starting parallel storage polling instance=Cluster onlineNodes=4 totalNodes=4
8:05PM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=XX1
8:05PM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=XX2
8:05PM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=XX3
8:05PM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=XX4

```

**Comment by PlayrTBH** [comment]
Seeing this, it's probably important for me to note that I use ZFS for all storage on each node. But this is the same as above for me.

**Comment by laurentpellet** [comment]
v4.2 is functional
Nodes are unhealthy, but it's working

```
8:53PM INF Background discovery scan completed errors=0 servers=4
8:53PM WRN Marking cluster node as unhealthy cluster=cluster endpoint=https://IP3:8006
8:53PM WRN Marking cluster node as unhealthy cluster=cluster endpoint=https://IP1:8006
8:53PM WRN Marking cluster node as unhealthy cluster=cluster endpoint=https://IP2:8006
8:53PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse-monitor@pam!pulse-token realm=pam tokenName=pulse-token user=pulse-monitor
8:53PM INF Recovered unhealthy cluster node cluster=cluster endpoint=https://IP1:8006
8:53PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse-monitor@pam!pulse-token realm=pam tokenName=pulse-token user=pulse-monitor
8:53PM INF Recovered unhealthy cluster node cluster=cluster endpoint=https://IP3:8006
8:53PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse-monitor@pam!pulse-token realm=pam tokenName=pulse-token user=pulse-monitor
8:53PM INF Recovered unhealthy cluster node cluster=cluster endpoint=https://IP2:8006
8:53PM INF Parsed authentication details hasTokenValue=true originalTokenName=pulse-monitor@pam!pulse-token realm=pam tokenName=pulse-token user=pulse-monitor
8:53PM INF Recovered unhealthy cluster node cluster=cluster endpoint=https://IP4:8006
8:53PM WRN Marking cluster node as unhealthy cluster=cluster endpoint=https://IP1:8006
8:53PM INF Broadcasting state update (ticker) containers=8 nodes=4 pbs=0 pbsBackups=0 vms=49
```

**Comment by rcourtman** [comment]
@laurentpellet @PlayrTBH  could you go to Settings > Diagnostics section > click "Run Diagnostics" and share the output? that'll give help me debug this

**Comment by laurentpellet** [comment]
### 4.12.1

```json
{
  "timestamp": "2025-09-02T00:20:51.691Z",
  "version": "2.0.0",
  "environment": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0",
    "platform": "Win32",
    "language": "fr",
    "screenResolution": "1920x1080",
    "windowSize": "1920x995",
    "timeZone": "Pacific/Honolulu"
  },
  "websocket": {
    "connected": true,
    "url": "ws://REDACTED/ws"
  },
  "nodes": [
    {
      "id": "pve-0",
      "type": "pve",
      "name": "node-REDACTED",
      "host": "https://REDACTED:8006",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "fingerprint": "C6:E0:9B:AC:D1:5D:68:09:5E:44:7D:52:C8:B7:D9:D8:30:42:37:70:9D:2A:99:43:C3:87:0B:35:DC:30:DF:60",
      "verifySSL": false,
      "monitorVMs": true,
      "monitorContainers": true,
      "monitorStorage": true,
      "monitorBackups": true,
      "status": "disconnected",
      "isCluster": true,
      "clusterName": "cluster-REDACTED",
      "clusterEndpoints": [
        {
          "NodeID": "node/dl360-hv7",
          "NodeName": "node-1",
          "Host": "node-1",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-02T00:20:14.29115979Z"
        },
        {
          "NodeID": "node/dl360-hv8",
          "NodeName": "node-2",
          "Host": "node-2",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-02T00:20:14.291159867Z"
        },
        {
          "NodeID": "node/dellR530",
          "NodeName": "node-3",
          "Host": "node-3",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-02T00:20:14.29116008Z"
        },
        {
          "NodeID": "node/dl360-hv9",
          "NodeName": "node-4",
          "Host": "node-4",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-02T00:20:14.291160158Z"
        }
      ]
    }
  ],
  "state": {
    "nodesCount": 4,
    "vmsCount": 40,
    "containersCount": 8,
    "storageCount": 0,
    "pbsCount": 0,
    "pbsBackupsCount": 0,
    "pveBackups": {
      "backupTasksCount": 0,
      "storageBackupsCount": 0,
      "guestSnapshotsCount": 0
    }
  },
  "storage": [],
  "backups": {
    "pveBackupTasks": [],
    "pveStorageBackups": [],
    "pbsBackups": []
  },
  "connectionHealth": {
    "Cluster": false
  },
  "performance": {
    "lastPollDuration": 0.000101562,
    "totalApiCalls": 0,
    "failedApiCalls": 0,
    "apiCallDuration": {}
  },
  "activeAlerts": [],
  "settings": {},
  "_notice": "This diagnostic data has been sanitized for sharing on GitHub. IP addresses, hostnames, and tokens have been redacted."
}
```

and some diff with 4.2 diagnostics file

<img width="1474" height="626" alt="Image" src="https://github.com/user-attachments/assets/2e951f36-22ce-459b-8711-b4b62e2909ad" />

**Comment by laurentpellet** [comment]
curl -k https://your_pve_ip:8006/api2/json/nodes (with your auth)

<img width="315" height="937" alt="Image" src="https://github.com/user-attachments/assets/b9c092fb-0e7e-4f08-980f-76d5a684eb63" />

Pulse log starting up in docker

```
12:45AM INF WebSocket upgrade request host=xxx:7655 origin=http://xxx:7655 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
12:45AM INF WebSocket client created client=client-1756773925767728749
12:45AM INF ReadPump started client=client-1756773925767728749
12:45AM INF WebSocket client connected client=client-1756773925767728749
12:45AM INF WritePump started client=client-1756773925767728749
12:45AM INF Sending welcome message client=client-1756773925503342893
12:45AM INF Welcome message sent client=client-1756773925503342893
12:45AM INF Sending initial state to client client=client-1756773925503342893 dataKB=3 dataLen=3625
12:45AM INF Initial state sent successfully client=client-1756773925503342893
12:45AM INF Sending welcome message client=client-1756773925767728749
12:45AM INF Welcome message sent client=client-1756773925767728749
12:45AM INF Polling VMs and containers using cluster/resources instance=Cluster
12:45AM INF Sending initial state to client client=client-1756773925767728749 dataKB=3 dataLen=3625
12:45AM INF Initial state sent successfully client=client-1756773925767728749
12:45AM INF Successfully retrieved disk usage from guest agent (cluster/resources showed 0) instance=Cluster totalBytes=33781968896 usage=63.66264361384367 usedBytes=21506494464 vm=DC2
cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} memory={"clear":80,"trigger":85}
12:45AM INF Checking guest thresholds cpu=9.852897323418611 disk=63.66264361384367 guest=DC2 memory=79.2960625141859 thresholds=
12:45AM INF System settings loaded file=/data/system.json
12:45AM INF System settings loaded file=/data/system.json
12:45AM INF System settings loaded file=/data/system.json
12:45AM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://172.16.00.00:8006
12:45AM WRN Failed on cluster node, trying next error="API error 500: {\"data\":null,\"message\":\"QEMU guest agent is not running\\n\"}" attempt=1 cluster=Cluster endpoint=https://172.16.00.00:8006
cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} memory={"clear":80,"trigger":85}
12:45AM INF Checking guest thresholds cpu=1.40711619304847 disk=-1 guest=DC1 memory=76.89962175001963 thresholds=
cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} memory={"clear":80,"trigger":85}
...
... other vms
...
12:45AM INF Checking guest thresholds cpu=3.2068947061782898 disk=-1 guest=DOCKERLAB04 memory=47.93357849121094 thresholds=
cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} memory={"clear":80,"trigger":85}
12:45AM INF Checking guest thresholds cpu=2.24110900348176 disk=-1 guest=OPENMETADATA memory=91.83573722839355 thresholds=
12:45AM INF VMs and containers polled efficiently with cluster/resources containers=8 instance=Cluster vms=40
12:45AM WRN Failed to get cluster storage config - will continue with node storage only error="no healthy nodes available in cluster Cluster" instance=Cluster
12:45AM INF Starting parallel storage polling instance=Cluster onlineNodes=4 totalNodes=4
12:45AM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=dl360-hv8
12:45AM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=dellR530
12:45AM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=dl360-hv7
12:45AM WRN Failed to get node storage error="no healthy nodes available in cluster Cluster" node=dl360-hv9
12:45AM INF Parallel storage polling completed duration=0.140615 failedNodes=4 instance=Cluster successfulNodes=0 totalStorage=0
12:45AM INF Starting background backup/snapshot polling instance=Cluster
12:45AM ERR Failed to get backup tasks error="get_backup_tasks failed on Cluster: no healthy nodes available in cluster Cluster" instance=Cluster
12:45AM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv8: no healthy nodes available in cluster Cluster" node=dl360-hv8
12:45AM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dellR530: no healthy nodes available in cluster Cluster" node=dellR530
12:45AM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv7: no healthy nodes available in cluster Cluster" node=dl360-hv7
12:45AM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv9: no healthy nodes available in cluster Cluster" node=dl360-hv9
12:45AM INF Completed background backup/snapshot polling instance=Cluster

```


### Proxmox Version

V8.4.5

### Auth

OK with token

### Permissions

<img width="501" height="991" alt="Image" src="https://github.com/user-attachments/assets/18340eec-eec6-4819-abdd-38cd14e1b7e2" />

v4.3.8 broke the snapshots (but PVE backup are still working)

**Comment by PlayrTBH** [comment]
Heres my diagnostic output:

{
  "timestamp": "2025-09-02T04:06:19.054Z",
  "version": "2.0.0",
  "environment": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "platform": "Win32",
    "language": "en-US",
    "screenResolution": "1080x1920",
    "windowSize": "1078x767",
    "timeZone": "America/New_York"
  },
  "websocket": {
    "connected": true,
    "url": "ws://REDACTED/ws"
  },
  "nodes": [
    {
      "id": "pve-0",
      "type": "pve",
      "name": "node-REDACTED.local",
      "host": "https://REDACTED:8006",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorVMs": true,
      "monitorContainers": true,
      "monitorStorage": true,
      "monitorBackups": true,
      "status": "disconnected",
      "isCluster": true,
      "clusterName": "cluster-REDACTED",
      "clusterEndpoints": [
        {
          "NodeID": "node/pve",
          "NodeName": "node-1",
          "Host": "node-1",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-01T18:50:15.088897014Z"
        },
        {
          "NodeID": "node/pve1",
          "NodeName": "node-2",
          "Host": "node-2",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-01T18:50:15.088897589Z"
        },
        {
          "NodeID": "node/pve2",
          "NodeName": "node-3",
          "Host": "node-3",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-01T18:50:15.088898148Z"
        }
      ]
    },
    {
      "id": "pbs-1",
      "type": "pbs",
      "name": "node-REDACTED",
      "host": "https://REDACTED:8007",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorDatastores": true,
      "monitorSyncJobs": true,
      "monitorVerifyJobs": true,
      "monitorPruneJobs": true,
      "status": "connected"
    }
  ],
  "state": {
    "nodesCount": 3,
    "vmsCount": 8,
    "containersCount": 0,
    "storageCount": 0,
    "pbsCount": 1,
    "pbsBackupsCount": 779,
    "pveBackups": {
      "backupTasksCount": 0,
      "storageBackupsCount": 0,
      "guestSnapshotsCount": 0
    }
  },
  "storage": [],
  "backups": {
    "pveBackupTasks": [],
    "pveStorageBackups": [],
    "pbsBackups": [
      {
        "backupTime": "2025-09-02T04:00:27Z",
        "backupType": "vm",
        "comment": "VaultWarden",
        "datastore": "datastore-0",
        "files": [
          "qemu-server.conf.blob",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-106-1756785627",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 137438954269,
        "verified": false,
        "vmid": "106"
      },
      {
        "backupTime": "2025-09-02T04:00:18Z",
        "backupType": "vm",
        "comment": "TrueNas",
        "datastore": "datastore-1",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio1.img.fidx",
          "drive-virtio0.img.fidx",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-103-1756785618",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 5703716570044,
        "verified": false,
        "vmid": "103"
      },
      {
        "backupTime": "2025-09-02T04:00:08Z",
        "backupType": "vm",
        "comment": "WS-2022",
        "datastore": "datastore-2",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio1.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-100-1756785608",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 275101270823,
        "verified": false,
        "vmid": "100"
      },
      {
        "backupTime": "2025-09-02T04:00:05Z",
        "backupType": "vm",
        "comment": "RLY",
        "datastore": "datastore-3",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-107-1756785605",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 68719477527,
        "verified": false,
        "vmid": "107"
      },
      {
        "backupTime": "2025-09-02T04:00:03Z",
        "backupType": "vm",
        "comment": "MCSManager",
        "datastore": "datastore-4",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-105-1756785603",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 137438954280,
        "verified": false,
        "vmid": "105"
      },
      {
        "backupTime": "2025-09-02T04:00:01Z",
        "backupType": "vm",
        "comment": "Veeam",
        "datastore": "datastore-5",
        "files": [
          "qemu-server.conf.blob",
          "drive-tpmstate0-backup.img.fidx",
          "drive-ide0.img.fidx",
          "drive-efidisk0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-104-1756785601",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 68724212738,
        "verified": false,
        "vmid": "104"
      },
      {
        "backupTime": "2025-09-02T04:00:01Z",
        "backupType": "vm",
        "comment": "Pulse",
        "datastore": "datastore-6",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-102-1756785601",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 34359739160,
        "verified": false,
        "vmid": "102"
      },
      {
        "backupTime": "2025-09-02T03:45:48Z",
        "backupType": "vm",
        "comment": "VaultWarden",
        "datastore": "datastore-7",
        "files": [
          "qemu-server.conf.blob",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-106-1756784748",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 137438954269,
        "verified": false,
        "vmid": "106"
      },
      {
        "backupTime": "2025-09-02T03:45:27Z",
        "backupType": "vm",
        "comment": "TrueNas",
        "datastore": "datastore-8",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio1.img.fidx",
          "drive-virtio0.img.fidx",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-103-1756784727",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 5703716570040,
        "verified": false,
        "vmid": "103"
      },
      {
        "backupTime": "2025-09-02T03:45:13Z",
        "backupType": "vm",
        "comment": "RLY",
        "datastore": "datastore-9",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-107-1756784713",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 68719477524,
        "verified": false,
        "vmid": "107"
      }
    ]
  },
  "connectionHealth": {
    "pbs-pbs.cfl.rr.com": true,
    "pve.local": false
  },
  "performance": {
    "lastPollDuration": 0.384137105,
    "totalApiCalls": 0,
    "failedApiCalls": 0,
    "apiCallDuration": {}
  },
  "activeAlerts": [],
  "settings": {},
  "_notice": "This diagnostic data has been sanitized for sharing on GitHub. IP addresses, hostnames, and tokens have been redacted."
}


And heres the user permissions:

root@pve:~ pveum user permissions pulse-monitor@pam
┌────────────────┬────────────────────────────────┐
│ ACL path       │ Permissions                    │
╞════════════════╪════════════════════════════════╡
│ /              │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /access        │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /access/groups │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /nodes         │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /pool          │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /sdn           │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
├────────────────┼────────────────────────────────┤
│ /storage       │ Datastore.Allocate (*)         │
│                │ Datastore.AllocateSpace (*)    │
│                │ Datastore.AllocateTemplate (*) │
│                │ Datastore.Audit (*)            │
├────────────────┼────────────────────────────────┤
│ /vms           │ Datastore.Audit (*)            │
│                │ Mapping.Audit (*)              │
│                │ Pool.Audit (*)                 │
│                │ SDN.Audit (*)                  │
│                │ Sys.Audit (*)                  │
│                │ VM.Audit (*)                   │
│                │ VM.Monitor (*)                 │
└────────────────┴────────────────────────────────┘
Permissions marked with '(*)' have the 'propagate' flag set.
root@pve:~

Proxmox version is 8.4.12

**Comment by jiriteach** [comment]
Fresh install and am seeing the same issue!

**Comment by rcourtman** [comment]
could you test v4.14.0-rc.1 and see if this is fixed

**Comment by PlayrTBH** [comment]
Just pulled 14.0, appears to still be occuring, noticed this log which I don't believe I've seen before:

5:22PM WRN Marking cluster node as unhealthy cluster=pve.local endpoint=https://192.168.1.47:8006
5:22PM WRN Failed on cluster node, trying next error="API error 500: {\"data\":null,\"message\":\"No QEMU guest agent configured\\n\"}" attempt=1 cluster=pve.local endpoint=https://192.168.1.47:8006
5:22PM WRN Marking cluster node as unhealthy cluster=pve.local endpoint=https://192.168.1.170:8006
5:22PM WRN Failed on cluster node, trying next error="API error 500: {\"data\":null,\"message\":\"No QEMU guest agent configured\\n\"}" attempt=2 cluster=pve.local endpoint=https://192.168.1.170:8006
5:22PM WRN Marking cluster node as unhealthy cluster=pve.local endpoint=https://192.168.1.198:8006
5:22PM WRN Failed on cluster node, trying next error="API error 500: {\"message\":\"No QEMU guest agent configured\\n\",\"data\":null}" attempt=3 cluster=pve.local endpoint=https://192.168.1.198:8006

Besides this, I do still get the original errors

5:22PM WRN Failed to get cluster storage config - will continue with node storage only error="no healthy nodes available in cluster pve.local" instance=pve.local
5:22PM INF Starting parallel storage polling instance=pve.local onlineNodes=3 totalNodes=3
5:22PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster pve.local" instance=pve.local node=pve
5:22PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster pve.local" instance=pve.local node=pve1
5:22PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster pve.local" instance=pve.local node=pve2
5:22PM ERR All nodes failed to retrieve storage - check Proxmox API permissions for Datastore.Audit on all storage failedNodes=3 instance=pve.local
5:22PM INF Starting background backup/snapshot polling instance=pve.local
5:22PM ERR Failed to get backup tasks error="get_backup_tasks failed on pve.local: no healthy nodes available in cluster pve.local" instance=pve.local
5:22PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on pve.local/pve: no healthy nodes available in cluster pve.local" node=pve
5:22PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on pve.local/pve1: no healthy nodes available in cluster pve.local" node=pve1
5:22PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on pve.local/pve2: no healthy nodes available in cluster pve.local" node=pve2
5:22PM INF Completed background backup/snapshot polling instance=pve.local

(timezone is wrong on this but this is the latest) 

Heres diagnostics if needed again:

{
  "timestamp": "2025-09-04T17:25:15.982Z",
  "version": "2.0.0",
  "environment": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "platform": "Win32",
    "language": "en-US",
    "screenResolution": "2048x1152",
    "windowSize": "2048x983",
    "timeZone": "America/New_York"
  },
  "websocket": {
    "connected": true,
    "url": "ws://REDACTED/ws"
  },
  "nodes": [
    {
      "id": "pve-0",
      "type": "pve",
      "name": "node-REDACTED.local",
      "host": "https://REDACTED:8006",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorVMs": true,
      "monitorContainers": true,
      "monitorStorage": true,
      "monitorBackups": true,
      "status": "connected",
      "isCluster": true,
      "clusterName": "cluster-REDACTED",
      "clusterEndpoints": [
        {
          "NodeID": "node/pve1",
          "NodeName": "node-1",
          "Host": "node-1",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:24:55.873457514Z"
        },
        {
          "NodeID": "node/pve",
          "NodeName": "node-2",
          "Host": "node-2",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:24:55.873457616Z"
        },
        {
          "NodeID": "node/pve2",
          "NodeName": "node-3",
          "Host": "node-3",
          "IP": "192.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:24:55.873457677Z"
        }
      ]
    },
    {
      "id": "pbs-1",
      "type": "pbs",
      "name": "node-REDACTED",
      "host": "https://REDACTED:8007/",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorDatastores": true,
      "monitorSyncJobs": true,
      "monitorVerifyJobs": true,
      "monitorPruneJobs": true,
      "status": "connected"
    }
  ],
  "state": {
    "nodesCount": 3,
    "vmsCount": 10,
    "containersCount": 0,
    "storageCount": 0,
    "pbsCount": 1,
    "pbsBackupsCount": 1439,
    "pveBackups": {
      "backupTasksCount": 0,
      "storageBackupsCount": 0,
      "guestSnapshotsCount": 0
    }
  },
  "storage": [],
  "backups": {
    "pveBackupTasks": [],
    "pveStorageBackups": [],
    "pbsBackups": [
      {
        "backupTime": "2025-09-04T17:15:26Z",
        "backupType": "vm",
        "comment": "Kali",
        "datastore": "datastore-0",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-109-1757006126",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 274877907779,
        "verified": false,
        "vmid": "109"
      },
      {
        "backupTime": "2025-09-04T17:15:22Z",
        "backupType": "vm",
        "comment": "VaultWarden",
        "datastore": "datastore-1",
        "files": [
          "qemu-server.conf.blob",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-106-1757006122",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 137438954268,
        "verified": false,
        "vmid": "106"
      },
      {
        "backupTime": "2025-09-04T17:15:17Z",
        "backupType": "vm",
        "comment": "TrueNas",
        "datastore": "datastore-2",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio1.img.fidx",
          "drive-virtio0.img.fidx",
          "drive-scsi0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-103-1757006117",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 5703716570044,
        "verified": false,
        "vmid": "103"
      },
      {
        "backupTime": "2025-09-04T17:15:09Z",
        "backupType": "vm",
        "comment": "WS-2022",
        "datastore": "datastore-3",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio1.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-100-1757006109",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 275101270819,
        "verified": false,
        "vmid": "100"
      },
      {
        "backupTime": "2025-09-04T17:15:08Z",
        "backupType": "vm",
        "comment": "MacBackup",
        "datastore": "datastore-4",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-108-1757006108",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 34359739162,
        "verified": false,
        "vmid": "108"
      },
      {
        "backupTime": "2025-09-04T17:15:06Z",
        "backupType": "vm",
        "comment": "RLY",
        "datastore": "datastore-5",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-107-1757006106",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 68719477524,
        "verified": false,
        "vmid": "107"
      },
      {
        "backupTime": "2025-09-04T17:15:04Z",
        "backupType": "vm",
        "comment": "MCSManager",
        "datastore": "datastore-6",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-105-1757006104",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 137438954281,
        "verified": false,
        "vmid": "105"
      },
      {
        "backupTime": "2025-09-04T17:15:02Z",
        "backupType": "vm",
        "comment": "Pulse",
        "datastore": "datastore-7",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-102-1757006102",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 34359739156,
        "verified": false,
        "vmid": "102"
      },
      {
        "backupTime": "2025-09-04T17:15:00Z",
        "backupType": "vm",
        "comment": "Veeam",
        "datastore": "datastore-8",
        "files": [
          "qemu-server.conf.blob",
          "drive-tpmstate0-backup.img.fidx",
          "drive-ide0.img.fidx",
          "drive-efidisk0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-104-1757006100",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 68724212742,
        "verified": false,
        "vmid": "104"
      },
      {
        "backupTime": "2025-09-04T17:00:25Z",
        "backupType": "vm",
        "comment": "Kali",
        "datastore": "datastore-9",
        "files": [
          "qemu-server.conf.blob",
          "drive-virtio0.img.fidx",
          "index.json.blob",
          "client.log.blob"
        ],
        "id": "pbs-pbs.cfl.rr.com-Backups--vm-109-1757005225",
        "instance": "pbs.cfl.rr.com",
        "namespace": "",
        "owner": "root@pam",
        "protected": false,
        "size": 274877907777,
        "verified": false,
        "vmid": "109"
      }
    ]
  },
  "connectionHealth": {
    "pbs-pbs.cfl.rr.com": true,
    "pve.local": false
  },
  "performance": {
    "lastPollDuration": 0.478092423,
    "totalApiCalls": 0,
    "failedApiCalls": 0,
    "apiCallDuration": {}
  },
  "activeAlerts": [],
  "settings": {},
  "_notice": "This diagnostic data has been sanitized for sharing on GitHub. IP addresses, hostnames, and tokens have been redacted."
}

**Comment by rcourtman** [comment]
thanks for testing. i see the issue now - the guest agent errors are marking nodes as unhealthy unnecessarily. working on a fix

**Comment by rcourtman** [comment]
actually, try pulling v4.14.0-rc.1 again now - just pushed a fix for the QEMU agent issue without making a new release

**Comment by laurentpellet** [comment]
for info, my diagnostics in v4.14.0-rc.1

```json
{
  "timestamp": "2025-09-04T17:47:38.631Z",
  "version": "2.0.0",
  "environment": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0",
    "platform": "Win32",
    "language": "fr",
    "screenResolution": "1920x1080",
    "windowSize": "1920x947",
    "timeZone": "Pacific/Honolulu"
  },
  "websocket": {
    "connected": true,
    "url": "ws://REDACTED/ws"
  },
  "nodes": [
    {
      "id": "pve-0",
      "type": "pve",
      "name": "node-REDACTED.local",
      "host": "https://REDACTED:8006",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorVMs": true,
      "monitorContainers": true,
      "monitorStorage": true,
      "monitorBackups": true,
      "status": "disconnected",
      "isCluster": true,
      "clusterName": "cluster-REDACTED",
      "clusterEndpoints": [
        {
          "NodeID": "node/dl360-hv7",
          "NodeName": "node-1",
          "Host": "node-1",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:46:08.628709362Z"
        },
        {
          "NodeID": "node/dl360-hv9",
          "NodeName": "node-2",
          "Host": "node-2",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:46:08.628709764Z"
        },
        {
          "NodeID": "node/dellR530",
          "NodeName": "node-3",
          "Host": "node-3",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:46:08.628710018Z"
        },
        {
          "NodeID": "node/dl360-hv8",
          "NodeName": "node-4",
          "Host": "node-4",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-04T17:46:08.628710418Z"
        }
      ]
    }
  ],
  "state": {
    "nodesCount": 4,
    "vmsCount": 40,
    "containersCount": 8,
    "storageCount": 0,
    "pbsCount": 0,
    "pbsBackupsCount": 0,
    "pveBackups": {
      "backupTasksCount": 0,
      "storageBackupsCount": 0,
      "guestSnapshotsCount": 0
    }
  },
  "storage": [],
  "backups": {
    "pveBackupTasks": [],
    "pveStorageBackups": [],
    "pbsBackups": []
  },
  "connectionHealth": {
    "dl360-hv7.proxmox.ispf.local": false
  },
  "performance": {
    "lastPollDuration": 0.000088314,
    "totalApiCalls": 0,
    "failedApiCalls": 0,
    "apiCallDuration": {}
  },
  "activeAlerts": [],
  "settings": {},
  "_notice": "This diagnostic data has been sanitized for sharing on GitHub. IP addresses, hostnames, and tokens have been redacted."
}
```

**Comment by laurentpellet** [comment]
Pulled v4.14.0-rc.1 again, still no storage...

<img width="1330" height="117" alt="Image" src="https://github.com/user-attachments/assets/599498ab-efb9-457a-af45-012905c10713" />

**Comment by PlayrTBH** [comment]
I have pulled 4.14.0-rc.2 and this appears to now be fixed. No errors inside of docker logs and I do see storage showing now.

**Comment by jiriteach** [comment]
I pulled image: rcourtman/pulse:v4.14.0-rc.2 and still seeing issues.
All was working a few versions ago.

I have completely flushed config and setup Pulse again.

Nothing wrong with my PVE. 
Both are healthy and working.

```
4:19PM ERR Failed to get nodes error="poll_nodes failed on NOOBER - PVE: no healthy nodes available in cluster NOOBER - PVE" instance="NOOBER - PVE"
4:19PM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster ZOOBER" cluster=ZOOBER
4:19PM ERR Failed to get nodes error="poll_nodes failed on ZOOBER: no healthy nodes available in cluster ZOOBER" instance=ZOOBER
```

**Comment by laurentpellet** [comment]
same here, not working

### Starting logs

```` 
6:47PM INF Sessions loaded from disk loaded=0 total=0
6:47PM INF CSRF tokens loaded from disk loaded=0 total=0
6:47PM INF System settings loaded file=/data/system.json
6:47PM INF Started watching .env file for changes path=/data/.env
6:47PM INF Server listening host=0.0.0.0 port=7655 protocol=HTTP
6:47PM INF ClusterClient.GetNodes succeeded cluster=Cluster count=4
dellR530=true dellR530=true dl360-hv7=true dellR530=true dellR530=true dl360-hv7=true dl360-hv8=true dellR530=true dellR530=true dl360-hv7=true dellR530=true dellR530=true dl360-hv7=true dl360-hv8=true dl360-hv9=true
6:47PM INF Starting alert cleanup for non-existent nodes existingNodes=4 nodes=totalAlerts=18
6:47PM INF No alerts needed cleanup
6:47PM INF Polling VMs and containers using cluster/resources instance=Cluster
...
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.63:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=1 cluster=Cluster endpoint=https://X.X.63:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.62:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=2 cluster=Cluster endpoint=https://X.X.62:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.64:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=3 cluster=Cluster endpoint=https://X.X.64:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.61:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=4 cluster=Cluster endpoint=https://X.X.61:8006
6:47PM INF VM with high memory detected in CheckGuest memUsage=85.0046870415099 status=running vm=OPNSENSE1
cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} cpu={"clear":75,"trigger":80} cpu={"clear":75,"trigger":80} disk={"clear":85,"trigger":90} memory={"clear":80,"trigger":85}
6:47PM INF Checking guest thresholds cpu=21.442588700452898 disk=-1 guest=OPNSENSE1 memory=85.0046870415099 thresholds=
6:47PM INF Recovered unhealthy cluster node cluster=Cluster endpoint=https://X.X.64:8006
6:47PM INF Recovered unhealthy cluster node cluster=Cluster endpoint=https://X.X.63:8006
6:47PM INF Recovered unhealthy cluster node cluster=Cluster endpoint=https://X.X.61:8006
6:47PM INF Recovered unhealthy cluster node cluster=Cluster endpoint=https://X.X.62:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.63:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=1 cluster=Cluster endpoint=https://X.X.63:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.61:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=2 cluster=Cluster endpoint=https://X.X.61:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.64:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=3 cluster=Cluster endpoint=https://X.X.64:8006
6:47PM WRN Marking cluster node as unhealthy cluster=Cluster endpoint=https://X.X.62:8006
6:47PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=4 cluster=Cluster endpoint=https://X.X.62:8006
...
6:47PM INF Checking guest thresholds cpu=2.24447761790645 disk=-1 guest=OPENMETADATA memory=88.05365562438965 thresholds=
6:47PM INF VMs and containers polled efficiently with cluster/resources containers=8 instance=Cluster vms=40
6:47PM WRN Failed to get cluster storage config - will continue with node storage only error="no healthy nodes available in cluster Cluster" instance=Cluster
6:47PM INF Starting parallel storage polling instance=Cluster onlineNodes=4 totalNodes=4
6:47PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster Cluster" instance=Cluster node=dellR530
6:47PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster Cluster" instance=Cluster node=dl360-hv7
6:47PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster Cluster" instance=Cluster node=dl360-hv8
6:47PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster Cluster" instance=Cluster node=dl360-hv9
6:47PM ERR All nodes failed to retrieve storage - check Proxmox API permissions for Datastore.Audit on all storage failedNodes=4 instance=Cluster
6:47PM INF Starting background backup/snapshot polling instance=Cluster
6:47PM ERR Failed to get backup tasks error="get_backup_tasks failed on Cluster: no healthy nodes available in cluster Cluster" instance=Cluster
6:47PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dellR530: no healthy nodes available in cluster Cluster" node=dellR530
6:47PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv9: no healthy nodes available in cluster Cluster" node=dl360-hv9
6:47PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv7: no healthy nodes available in cluster Cluster" node=dl360-hv7
6:47PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on Cluster/dl360-hv8: no healthy nodes available in cluster Cluster" node=dl360-hv8
6:47PM INF Completed background backup/snapshot polling instance=Cluster
```` 

### Diagnostics file

```json
{
  "timestamp": "2025-09-05T18:52:49.056Z",
  "version": "2.0.0",
  "environment": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0",
    "platform": "Win32",
    "language": "fr",
    "screenResolution": "2560x1440",
    "windowSize": "2560x1355",
    "timeZone": "Pacific/Honolulu"
  },
  "websocket": {
    "connected": true,
    "url": "ws://REDACTED/ws"
  },
  "nodes": [
    {
      "id": "pve-0",
      "type": "pve",
      "name": "node-REDACTED",
      "host": "https://REDACTED:8006",
      "hasPassword": false,
      "tokenName": "token-REDACTED",
      "hasToken": true,
      "verifySSL": false,
      "monitorVMs": true,
      "monitorContainers": true,
      "monitorStorage": true,
      "monitorBackups": true,
      "status": "connected",
      "isCluster": true,
      "clusterName": "cluster-REDACTED",
      "clusterEndpoints": [
        {
          "NodeID": "node/dl360-hv7",
          "NodeName": "node-1",
          "Host": "node-1",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-05T18:52:21.356539273Z"
        },
        {
          "NodeID": "node/dl360-hv9",
          "NodeName": "node-2",
          "Host": "node-2",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-05T18:52:21.356539367Z"
        },
        {
          "NodeID": "node/dellR530",
          "NodeName": "node-3",
          "Host": "node-3",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-05T18:52:21.356539454Z"
        },
        {
          "NodeID": "node/dl360-hv8",
          "NodeName": "node-4",
          "Host": "node-4",
          "IP": "172.xxx.xxx.xxx",
          "Online": true,
          "LastSeen": "2025-09-05T18:52:21.356539562Z"
        }
      ]
    }
  ],
  "state": {
    "nodesCount": 4,
    "vmsCount": 40,
    "containersCount": 8,
    "storageCount": 0,
    "pbsCount": 0,
    "pbsBackupsCount": 0,
    "pveBackups": {
      "backupTasksCount": 0,
      "storageBackupsCount": 0,
      "guestSnapshotsCount": 0
    }
  },
  "storage": [],
  "backups": {
    "pveBackupTasks": [],
    "pveStorageBackups": [],
    "pbsBackups": []
  },
  "connectionHealth": {
    "Cluster": false
  },
  "performance": {
    "lastPollDuration": 0.000100347,
    "totalApiCalls": 0,
    "failedApiCalls": 0,
    "apiCallDuration": {}
  },
  "activeAlerts": [],
  "settings": {},
  "_notice": "This diagnostic data has been sanitized for sharing on GitHub. IP addresses, hostnames, and tokens have been redacted."
}
```

**Comment by SeeJayEmm** [comment]
RC2 has *improved* my situation but there are still issues.  Upon initial startup I'm still seeing errors and storage will be empty.
```
pulse  | 7:20PM WRN Failed to get cluster storage config - will continue with node storage only error="no healthy nodes available in cluster proxmox" instance=proxmox
pulse  | 7:20PM INF Starting parallel storage polling instance=proxmox onlineNodes=2 totalNodes=2
pulse  | 7:20PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster proxmox" instance=proxmox node=proxmox-05
pulse  | 7:20PM ERR Failed to get node storage - check API permissions error="no healthy nodes available in cluster proxmox" instance=proxmox node=proxmox-04
pulse  | 7:20PM ERR All nodes failed to retrieve storage - check Proxmox API permissions for Datastore.Audit on all storage failedNodes=2 instance=proxmox
pulse  | 7:20PM INF Starting background backup/snapshot polling instance=proxmox
pulse  | 7:20PM ERR Failed to get backup tasks error="get_backup_tasks failed on proxmox: no healthy nodes available in cluster proxmox" instance=proxmox
pulse  | 7:20PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on proxmox/proxmox-05: no healthy nodes available in cluster proxmox" node=proxmox-05
pulse  | 7:20PM WRN Failed to get storage for backups - skipping node error="get_storage_for_backups failed on proxmox/proxmox-04: no healthy nodes available in cluster proxmox" node
```

If I wait several minutes storage will eventually populate.  Once the storage has populated the node errors appear to go away but I see these repeating:

```
pulse  | 7:24PM WRN Marking cluster node as unhealthy cluster=proxmox endpoint=https://10.9.1.24:8006
pulse  | 7:24PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=1 cluster=proxmox endpoint=https://10.9.1.24:8006
pulse  | 7:24PM WRN Marking cluster node as unhealthy cluster=proxmox endpoint=https://10.9.1.25:8006
pulse  | 7:24PM WRN Failed on cluster node, trying next error="json: cannot unmarshal object into Go struct field .data.result of type []proxmox.VMFileSystem" attempt=2 cluster=proxmox endpoint=https://10.9.1.25:8006
```

[pulse-diagnostics-sanitized-2025-09-05.json](https://github.com/user-attachments/files/22179266/pulse-diagnostics-sanitized-2025-09-05.json)

**Comment by laurentpellet** [comment]
I can confirm that release v4.15.0-rc.2 fixed everything.
Good job !

**Comment by jiriteach** [comment]
Just tried 4.15.0-rc2 and its still throwing errors.

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/c7ff0865-bf96-4354-bad6-a58c42299776" />

<img width="548" height="621" alt="Image" src="https://github.com/user-attachments/assets/0f692f22-52fa-4208-9b10-21092bccf8c4" />

```
6:17AM ERR Failed to get nodes error="poll_nodes failed on NOOBER - PVE: no healthy nodes available in cluster NOOBER - PVE" instance="NOOBER - PVE"

6:17AM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster ZOOBER" cluster=ZOOBER

6:17AM ERR Failed to get nodes error="poll_nodes failed on ZOOBER: no healthy nodes available in cluster ZOOBER" instance=ZOOBER

6:17AM INF System settings loaded file=/data/system.json

6:17AM INF Broadcasting state update (ticker) containers=0 nodes=0 pbs=0 pbsBackups=0 vms=0

6:17AM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster NOOBER - PVE" cluster="NOOBER - PVE"

6:17AM ERR Failed to get nodes error="poll_nodes failed on NOOBER - PVE: no healthy nodes available in cluster NOOBER - PVE" instance="NOOBER - PVE"

6:17AM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster ZOOBER" cluster=ZOOBER

6:17AM ERR Failed to get nodes error="poll_nodes failed on ZOOBER: no healthy nodes available in cluster ZOOBER" instance=ZOOBER

6:17AM INF Broadcasting state update (ticker) containers=0 nodes=0 pbs=0 pbsBackups=0 vms=0

6:17AM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster ZOOBER" cluster=ZOOBER

6:17AM ERR Failed to get nodes error="poll_nodes failed on ZOOBER: no healthy nodes available in cluster ZOOBER" instance=ZOOBER

6:17AM WRN ClusterClient.GetNodes failed error="no healthy nodes available in cluster NOOBER - PVE" cluster="NOOBER - PVE"

6:17AM ERR Failed to get nodes error="poll_nodes failed on NOOBER - PVE: no healthy nodes available in cluster NOOBER - PVE" instance=
```

**Comment by laurentpellet** [comment]
> I can confirm that release v4.15.0-rc.2 fixed everything. Good job !

Ahh, no more snapshots. It was so close !
but VM disk size, and PVE backups are still ok..

**Comment by rcourtman** [comment]
@PlayrTBH this should be fixed in v4.15.0-rc.3 - could you test and confirm?

**Comment by jiriteach** [comment]
@rcourtman - Awesome, thanks. This is working now with rc3.

**Comment by laurentpellet** [comment]
Snapshots are still broken. Storage and PVE Backups OK
I can see that dark mode is not persisted through reloading... not making an issue for that..


> > I can confirm that release v4.15.0-rc.2 fixed everything. Good job !
> 
> Ahh, no more snapshots. It was so close ! but VM disk size, and PVE backups are still ok..

**Comment by cyberfox** [comment]
Greetings,
I am having this problem with 4.25.0. Is it a resurfacing of the same problem, or a new one?

I've removed and re-added the cluster several times. I thought it was because I had several nodes in 'maintenance' mode, but it wasn't that. I really have no idea why it lost my cluster. I think it happened not long after my upgrade to 4.25, but I'd jumped quite a few versions at that point. My Proxmox backup service recognizer is working just fine, and my cluster is (of course) working just fine. I thought it might be that I'm not running it on 8006 (I use Nginx Proxy Manager to make a nice URL for Proxmox, including a good TLS key) but that wasn't it. (I also eventually realized that I could specify :443 and the setup would stop trying to add :8006 onto the end.)

But Pulse refuses to accept that it's working. It shows all the nodes as online, but won't show the actual VMs and LXCs running on the hosts.

In the logs, the most relevant lines seem to be these:

```
Nov 01 06:15:01 pulse pulse[124]: {"level":"warn","component":"pulse-config","cluster":"Proxmox Homelab","error":"no healthy nodes available in cluster Proxmox Homelab","time":"2025-11-01T06:15:01Z","message":"ClusterClient.GetNodes failed"}
Nov 01 06:15:01 pulse pulse[124]: {"level":"error","component":"pulse-config","error":"poll_nodes failed on Proxmox Homelab: no healthy nodes available in cluster Proxmox Homelab","instance":"Proxmox Homelab","time":"2025-11-01T06:15:01Z","message":"Failed to get nodes"}
```

[pulse-diagnostics-sanitized-2025-11-01.json](https://github.com/user-attachments/files/23281103/pulse-diagnostics-sanitized-2025-11-01.json)

Thanks for any help; before I upgraded, it looked pretty good, with compact and useful info being shown!

--  Morgan

**Comment by rcourtman** [comment]
[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
