### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by FaboulousSan** [rcourtman/Pulse#414]
Probleme Proxmox 8 

<img width="1059" height="68" alt="Image" src="https://github.com/user-attachments/assets/00e276f0-f61c-4142-b448-4b8834e9532a" />

**Comment by Lion-killer** [comment]
Hi. After the latest update, I also tried connecting one of the nodes using a username and password (I’m on Proxmox 9.0.6). The QEMU agent is installed.

<img width="1224" height="57" alt="Image" src="https://github.com/user-attachments/assets/b6a5ded3-f78d-44da-b823-04900c6f398b" />

/api2/json/nodes/pve0/qemu/111/agent/get-fsinfo

```
{"data":{"result":[{"disk":[{"unit":0,"pci-controller":{"function":0,"slot":1,"bus":9,"domain":0},"bus-type":"sas","target":0,"dev":"\\\\.\\PhysicalDrive0","bus":0}],"name":"\\\\?\\Volume{e1d7a174-8989-4449-a63d-02756da44990}\\","type":"FAT32","mountpoint":"System Reserved"},{"disk":[{"pci-controller":{"domain":0,"bus":9,"slot":2,"function":0},"unit":1,"bus":0,"dev":"\\\\.\\PhysicalDrive1","target":0,"bus-type":"sas"}],"name":"\\\\?\\Volume{6ffcca76-aba3-4153-869e-19b31356747c}\\","type":"NTFS","total-bytes":107355303936,"used-bytes":23398965248,"mountpoint":"D:\\"},{"type":"NTFS","mountpoint":"System Reserved","disk":[{"pci-controller":{"function":0,"slot":1,"bus":9,"domain":0},"unit":0,"bus":0,"dev":"\\\\.\\PhysicalDrive0","target":0,"bus-type":"sas"}],"name":"\\\\?\\Volume{548b4200-09b5-4765-a9a9-c1972c2147a5}\\"},{"type":"NTFS","total-bytes":106482888704,"mountpoint":"C:\\","used-bytes":82643156992,"disk":[{"unit":0,"pci-controller":{"slot":1,"function":0,"bus":9,"domain":0},"target":0,"bus-type":"sas","dev":"\\\\.\\PhysicalDrive0","bus":0}],"name":"\\\\?\\Volume{4e7a1edc-e53b-4fd7-a3fa-fdce6c4bb192}\\"}]}}
```

**Comment by rcourtman** [comment]
could you test v4.14.0-rc.1 and see if this is fixed

**Comment by campodoro74** [comment]
Same with v4.14.0-rc.1

<img width="1338" height="1227" alt="Image" src="https://github.com/user-attachments/assets/e2d07d3c-7795-4cfb-a4a6-81af8aff8c94" />

**Comment by aroundmyroom** [comment]
no idea if it is related: I run [4.14.0-rc.2](https://github.com/rcourtman/Pulse/releases) now 
But when I have a VM and it shows me 7GB size and 7GB full I resized it, I rebooted the machine. but the storage is not updated in pulse

Even when I completely remove the cluster from pulse and re-add it, all information seems to be kept in the DB and when I add the cluster again its still on 7GB .. not ie. 16GB

**Comment by Lion-killer** [comment]
I installed v4.14.0-rc.2. The situation hasn’t changed: disk usage for virtual machines is not being displayed. How can I view the API request logs to help investigate the cause?

**Comment by aroundmyroom** [comment]
<img width="771" height="176" alt="Image" src="https://github.com/user-attachments/assets/53b2f457-7f6c-4b6e-a453-0c59d3382dc9" />

Here is mine .. I do have HDD size .. but it is not updated ;)

**Comment by FaboulousSan** [comment]
I installed the latest version (v4.14.0), and it’s still the same—nothing has changed.
Proxmox 8.4.12
What’s strange is that it used to work perfectly before. Could there be some cache or something else interfering?
I’d like to understand why it’s no longer working, even though all communications with the qemu agent seem fine (whether using a token or user credentials).

I am running in binary mode, not Docker.

Thanks for your great work.

**Comment by rcourtman** [comment]
@FaboulousSan which version did it work in before? thanks

**Comment by Lion-killer** [comment]
It worked for me in the [v4.12.1](https://github.com/rcourtman/Pulse/releases/tag/v4.12.1)

**Comment by FaboulousSan** [comment]
> [@FaboulousSan](https://github.com/FaboulousSan) which version did it work in before? thanks

@rcourtman "I think version v4.7.6 was working fine, as far as I remember. After that, other updates also worked, but I’m not sure when things started to go wrong, and I currently don’t have access to my test sandbox VM."

**Comment by FaboulousSan** [comment]
Good newsFor version v4.15.0-rc.2, it reports the total disk space where the VM is installed, not the VM's disk itself... but we’re getting closer.

<img width="448" height="126" alt="Image" src="https://github.com/user-attachments/assets/2cea2ffd-2b04-4f9d-9819-c459f97a29f8" />

Regarding the 0% issue: on OPNsense, the agent is properly installed, but nothing is being reported.

Where is the script mentioned in the release notes for v4.15.0-rc.2?

> Diagnostic Tools
> 
> New diagnostic script for troubleshooting VM disk issues:
> 
> # Run on your Pulse host
> /opt/pulse/scripts/test-vm-disk.sh <VMID>

**Comment by rcourtman** [comment]
@FaboulousSan this should be fixed in v4.15.0-rc.3 - could you test and confirm?

**Comment by FaboulousSan** [comment]
@rcourtman
I tested with version rc.5, but the issue persists.

<img width="675" height="103" alt="Image" src="https://github.com/user-attachments/assets/29fe9a80-1f83-4cba-a289-2d8de73a4a2c" />

For VM 109, it displays the wrong disk size—it should be 10GB, not 252GB, and the disk isn’t 2TB, it’s 4TB.
For VM 100, it correctly shows 60GB, but it doesn’t display the percentage usage.
Could there be a different logic for OPNsense’s QEMU agent?

Thanks for the work and this great solution!

**Comment by rcourtman** [comment]
[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
