### ISSUE TITLE
The same node names

### ISSUE THREAD

**Issue by KyKyLLIoHoK** [rcourtman/Pulse#476]
When adding multiple pve nodes with the same name, the following issues occur:
 - The VM count in the node list gives incorrect information for one of the nodes (details below)
 - The storage count in the node list gives incorrect information for one of the nodes (details below)
 - The VM and container list is incorrectly grouped 
 - The storage list is incorrectly grouped

To reproduce the error, add two pve nodes with the same name (in my example, "proxmox")

It is expected that the VM and container counts for each pve node will be displayed correctly, and the storage and VM/container lists will be grouped by real nodes

 - Pulse Version: [4.14.0]
 - Installation Type: Docker

1. VM counter error
In the attached screenshot, you can see that the VM counter for both nodes is 3, although in reality, one node has 2 VMs and the other has 1
<img width="1330" height="239" alt="Image" src="https://github.com/user-attachments/assets/4ea5fefe-7dde-42d0-ba1b-13c2c93810d8" />

2. The attached screenshot shows that the storage count for both nodes is 5, although in reality one node has 4 storage and the other has 3.

<img width="1324" height="218" alt="Image" src="https://github.com/user-attachments/assets/597c774e-7c45-4cd5-92c8-9dcdf7c49807" />

3. In the VM/container list, all entities are grouped under the same node name, even though they are actually VMs of two nodes.

<img width="1293" height="242" alt="Image" src="https://github.com/user-attachments/assets/8ad8ee98-8b5b-4883-8861-5a80275ba83b" />

4. In the list of storage entities, all entities are grouped under the same node name, although they are actually storage entities of two nodes.

<img width="1315" height="321" alt="Image" src="https://github.com/user-attachments/assets/cc089ddb-36d6-4e5d-b381-d679df6366af" />

Actual lists of VMs and storage on nodes:

<img width="1657" height="378" alt="Image" src="https://github.com/user-attachments/assets/861cf717-9353-4517-af81-7fc5c719d289" />

<img width="1913" height="393" alt="Image" src="https://github.com/user-attachments/assets/3eb8ab00-413b-4b8b-9f7e-d681aacfcfe9" />

**Comment by rcourtman** [comment]
fixed in commit 5180b84d4. the issue was that the dashboard and storage views were grouping by node hostname instead of unique instance ID. when multiple nodes share the same hostname, this caused VMs/containers/storage from different nodes to be incorrectly grouped together. the fix ensures proper separation by using the unique instance identifier

**Comment by KyKyLLIoHoK** [comment]
> fixed in commit 5180b84d4. the issue was that the dashboard and storage views were grouping by node hostname instead of unique instance ID. when multiple nodes share the same hostname, this caused VMs/containers/storage from different nodes to be incorrectly grouped together. the fix ensures proper separation by using the unique instance identifier

I have updated to 4.16.0. The grouping of VMs and storage devices is indeed fixed. However, the counters for VMs and storage devices are not fixed. I have attached a screenshot.

<img width="1322" height="561" alt="Image" src="https://github.com/user-attachments/assets/6aaee66a-de35-4e9b-8190-ea17256a4aed" />

**Comment by KyKyLLIoHoK** [comment]
The grouping is also not fixed on the "Guest URLs" page

<img width="1327" height="703" alt="Image" src="https://github.com/user-attachments/assets/b7d2c3f9-a089-4e97-95eb-9cac60a5f602" />

**Comment by KyKyLLIoHoK** [comment]
The grouping on the thresholds. page is also not fixed. There is also no grouping of storages

<img width="1296" height="1284" alt="Image" src="https://github.com/user-attachments/assets/4e6a547d-d1cf-4064-804a-14cd2dc2bab8" />

**Comment by alexunderboots** [comment]
Good day
Tell me how to switch the node display from "node" on the main screen to "node-name" (set when adding a node)?
I have many of the same names, but they all have different second-level domains.

**Comment by rcourtman** [comment]
[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
