### ISSUE TITLE
Restore from backup not working (4.26.3)

### ISSUE THREAD

**Issue by NightHawkATL** [rcourtman/Pulse#646]
**Describe the bug**
After updating to the latest version, I was trying to import from a docker instance I am using for work. I had made a backup from the docker instance and tried to restore from backup and got an error.

<img width="1314" height="672" alt="Image" src="https://github.com/user-attachments/assets/1feb329d-9f5a-4196-8399-a0719761a884" />

Inversely, I am seeing that on the docker instance, the password is not being taken when attempting a backup from an existing instance.

<img width="1317" height="711" alt="Image" src="https://github.com/user-attachments/assets/ae47f9c2-4188-4626-8836-b9f0ec6c0cb2" />

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Backups'
3. Click on 'Export backup'
4. try to export and put in the password and then see the error

**Expected behavior**
I expected the current instance to be restored from a backup and for the password to take when doing a backup.

**Environment:**
 - Pulse Version: [e.g. v4.26.3]
 - Installation Type: [e.g. ProxmoxVE LXC, Docker]

No errors shown in docker instance when trying to do a backup.

**Comment by rcourtman** [comment]
Fixed in v4.26.4. Config backup/restore failures have been resolved.

**Comment by NightHawkATL** [comment]
I am still getting the same error on 4.26.4. I will wait for the next release to see if it is still not working there.

**Comment by NightHawkATL** [comment]
Just updated to 4.26.5 and it still shows the same error on the backup export and restore import.

**Comment by rcourtman** [comment]
Sorry for the confusion—this failure happens when the login password is between 8 and 11 characters while backup encryption insists on 12+. The frontend now blocks the request before it ever reaches the backend, so nothing shows up in the logs. For now, either check "Use a custom passphrase" and enter a new 12+ character passphrase for the export, or change the login password to 12+ characters and then run the export. The minimum password length has been raised to 12 characters everywhere, so new users (and anyone changing passwords after the next release) won't be able to pick shorter passwords and will avoid this trap altogether.

**Comment by NightHawkATL** [comment]
I just tried changing the password to a 16-digit password with uppercase, lowercase, numbers, and symbols and it still gives the same error. If I am still missing something, please let me know.

<img width="1320" height="699" alt="Image" src="https://github.com/user-attachments/assets/663f85db-77a8-4ad4-8f6f-f984307406c3" />

**Comment by rcourtman** [comment]
The export failure came from two separate issues. First the browser stripped off the end of the security token because the UI only kept the part before the first `=`. Then the remaining value was still URL-encoded (browsers store `=` as `%3D` inside cookies), so the server refused it as invalid. Both problems are fixed in commit 7d4b5843d, so the full token now gets sent and exports succeed again. This will be in the next release.

**Comment by rcourtman** [comment]
[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
