### ISSUE TITLE
Windows Host Agent fails to start - Looking for Docker engine

### ISSUE THREAD

**Issue by DarthDogCow** [rcourtman/Pulse#766]
**Describe the bug**
The Windows Host Agent fails to start after installation.  It appears to be looking for Docker engine, even when --enable-docker is absent

**To Reproduce**
1.  Install Windows Agent without Docker support (tested on Windows 11 and Server 2022)
2. Agent fails to start
3. Copy command line from installed service
4. Run interactively via CLI
5. Errors attempting to find Docker will be seen (see below).  It looks like it's even failing back to trying UNIX sockets.

**Expected behavior**
Agent should start and report to Pulse server

**Environment:**
 - Pulse Version: 4.33.1
 - Installation Type: ProxmoxVE LXC

**Additional context**
PS C:\Users\warren\Downloads> . "C:\Program Files\Pulse\pulse-agent.exe" --url "http://[pulse_hostname]:7655" --token "[token]" --interval "30s" --enable-host
{"level":"info","version":"v4.33.1","pulse_url":"http://[pulse_hostname]:7655","host_agent":true,"docker_agent":true,"auto_update":true,"time":"2025-11-27T11:23:49Z","message":"Starting Pulse Unified Agent"}
{"level":"info","time":"2025-11-27T11:23:49Z","message":"Host agent module started"}
{"level":"fatal","error":"failed to connect to container runtime: environment defaults: error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.51/info\": open //./pipe/docker_engine: The system cannot find the file specified.; podman rootless socket: Cannot connect to the Docker daemon at unix:///run/user/-1/podman/podman.sock. Is the docker daemon running?; podman system socket: Cannot connect to the Docker daemon at unix:///run/podman/podman.sock. Is the docker daemon running?; default docker socket: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","time":"2025-11-27T11:23:49Z","message":"Failed to initialize docker agent"}

**Comment by rcourtman** [comment]
The log shows `docker_agent:true` even though `--enable-docker` wasn't specified. The unified agent checks the `PULSE_ENABLE_DOCKER` environment variable before looking at command-line flags.

Can you run these checks?

1. Check for the environment variable:
   ```powershell
   $env:PULSE_ENABLE_DOCKER
   [System.Environment]::GetEnvironmentVariable("PULSE_ENABLE_DOCKER", "Machine")
   [System.Environment]::GetEnvironmentVariable("PULSE_ENABLE_DOCKER", "User")
   ```

2. Show the installed service command line:
   ```powershell
   sc.exe qc PulseAgent
   ```

3. Which installer did you use? The unified installer at `/install.ps1` or the legacy at `/install-host-agent.ps1`?

If none of those environment variables are set and the service binary path doesn't include `--enable-docker`, there's a bug in the flag parsing that needs a closer look.

**Comment by DarthDogCow** [comment]
Aha!

The environment variable was set ($env:PULSE_ENABLE_DOCKER = “true”).

I was reusing a PWSH session where I’d previously run the “include Docker” installation command by mistake.

Now, in a fresh PWSH session…

  *
Remove service with sc.exe
  *
Install as per instructions
  *
Service fails to start ()
  *
When running the command defined in the Service rom the CLI, it works OK and reports home, so I suspect the SCM doesn’t know how to handle the service:

      Error 1053: The service did not respond to the start or control request in a timely fashion.

Regards,


Warren

***@***.***

From: rcourtman ***@***.***>
Date: Thursday, 27 November 2025 at 15:14
To: rcourtman/Pulse ***@***.***>
Cc: DarthDogCow ***@***.***>, Author ***@***.***>
Subject: Re: [rcourtman/Pulse] Windows Host Agent fails to start - Looking for Docker engine (Issue #766)

[https://avatars.githubusercontent.com/u/8825017?s=20&v=4]rcourtman left a comment (rcourtman/Pulse#766)<https://github.com/rcourtman/Pulse/issues/766#issuecomment-3586389169>

The log shows docker_agent:true even though --enable-docker wasn't specified. The unified agent checks the PULSE_ENABLE_DOCKER environment variable before looking at command-line flags.

Can you run these checks?

  1.  Check for the environment variable:

$env:PULSE_ENABLE_DOCKER
[System.Environment]::GetEnvironmentVariable("PULSE_ENABLE_DOCKER", "Machine")
[System.Environment]::GetEnvironmentVariable("PULSE_ENABLE_DOCKER", "User")

  2.  Show the installed service command line:

sc.exe qc PulseAgent

  3.  Which installer did you use? The unified installer at /install.ps1 or the legacy at /install-host-agent.ps1?

If none of those environment variables are set and the service binary path doesn't include --enable-docker, there's a bug in the flag parsing that needs a closer look.

**Comment by rcourtman** [comment]
Found the root cause.

The UI checkbox "Enable Docker monitoring" (in Settings → Unified Agents) defaults to **checked**. When you copy the installation command from the UI, it includes `$env:PULSE_ENABLE_DOCKER="true"` in the PowerShell command, which causes the agent to start with Docker monitoring enabled regardless of CLI flags.

This explains why `docker_agent:true` appeared in the log - the environment variable was set in the command you ran, even though `--enable-docker` was not explicitly passed.

The fix: Changed the default from `true` to `false` so users must explicitly opt-in to Docker monitoring. This will ship in the next release.

**Workaround for now:** When running the agent manually, ensure no `PULSE_ENABLE_DOCKER` environment variable is set:

```powershell
$env:PULSE_ENABLE_DOCKER = $null
& "C:\Program Files\Pulse\pulse-agent.exe" --url "http://..." --token "..." --interval "30s" --enable-host
```

Or reinstall using the UI command after unchecking "Enable Docker monitoring".

**Comment by DarthDogCow** [comment]
Yeah, I saw that too.

Even after reinstalling fresh with no environment variable, the SCM doesn’t seem to handle the service properly. I just sent a mail on that (I think our mails crossed).

Regards,


Warren

***@***.***

From: rcourtman ***@***.***>
Date: Thursday, 27 November 2025 at 15:35
To: rcourtman/Pulse ***@***.***>
Cc: DarthDogCow ***@***.***>, Author ***@***.***>
Subject: Re: [rcourtman/Pulse] Windows Host Agent fails to start - Looking for Docker engine (Issue #766)

[https://avatars.githubusercontent.com/u/8825017?s=20&v=4]rcourtman left a comment (rcourtman/Pulse#766)<https://github.com/rcourtman/Pulse/issues/766#issuecomment-3586480131>

Found the root cause.

The UI checkbox "Enable Docker monitoring" (in Settings → Unified Agents) defaults to checked. When you copy the installation command from the UI, it includes $env:PULSE_ENABLE_DOCKER="true" in the PowerShell command, which causes the agent to start with Docker monitoring enabled regardless of CLI flags.

This explains why docker_agent:true appeared in the log - the environment variable was set in the command you ran, even though --enable-docker was not explicitly passed.

The fix: Changed the default from true to false so users must explicitly opt-in to Docker monitoring. This will ship in the next release.

Workaround for now: When running the agent manually, ensure no PULSE_ENABLE_DOCKER environment variable is set:

$env:PULSE_ENABLE_DOCKER = $null
& "C:\Program Files\Pulse\pulse-agent.exe" --url "http://..." --token "..." --interval "30s" --enable-host

Or reinstall using the UI command after unchecking "Enable Docker monitoring".

**Comment by rcourtman** [comment]
Fix pushed in 6ff5ae42 - the UI now defaults "Enable Docker monitoring" to off. The install command you copy from the UI will no longer include `PULSE_ENABLE_DOCKER="true"` unless you explicitly check that box.

This will be in the next release.

**Comment by DarthDogCow** [comment]
Thanks.

Do I need to raise a separate bug report for the fact that the agent still doesn’t run as a service (it only runs interactively from the CLI)?

Regards,

Warren
***@***.***

**Comment by rcourtman** [comment]
Keep it in this issue - it's the same deployment scenario.

The unified agent (`pulse-agent`) is missing Windows service support. The legacy `pulse-host-agent` has it (`service_windows.go` with SCM integration), but that wasn't ported to the unified agent.

Error 1053 happens because the binary is registered as a Windows service via `sc.exe create`, but it never calls the Windows service APIs to signal it's started. The SCM waits 30 seconds then gives up. Interactive mode works because it doesn't need SCM integration.

This needs code changes to add Windows service support to `cmd/pulse-agent/`. Will track separately from the Docker env var issue that was fixed.

**Comment by rcourtman** [comment]
Windows service support has been added to the unified `pulse-agent` in cf62ebae.

The fix ports the SCM integration from the legacy `pulse-host-agent` to the unified agent. When running as a Windows service, the agent now properly handles start/stop commands and logs to Windows Event Log.

This will be included in the next release.

**Comment by DarthDogCow** [comment]
Fantastic, thanks!

Warren

**Comment by rcourtman** [comment]
Both issues are fixed:

1. **Docker env var defaulting to true** - Fixed in 6ff5ae42 (UI now defaults Docker checkbox to off)
2. **Windows service Error 1053** - Fixed in cf62ebae (added proper SCM integration to unified agent)

These will be in the next release. Closing since both problems are resolved.

**Comment by DarthDogCow** [comment]
Many thanks for this.

From reporting to resolution within 12 hours.  This is the sort of support I could only wish for from the major software vendors!

Regards,

Warren
***@***.***
