### ISSUE TITLE
PBS Data Not Loading with Multiple Instances Configured

### ISSUE THREAD

**Issue by Salan54** [rcourtman/Pulse#78]
I have the following configuration:

# .env file
PROXMOX_HOST=https://192.168.1.40:8006
PROXMOX_TOKEN_ID=pulse_monitor@pve!pulse
PROXMOX_TOKEN_SECRET=MySecret
PBS_HOST=https://192.168.1.232:8007
PBS_NODE_NAME=pbs3-1
PBS_TOKEN_ID=pulse-monitor@pbs!pulse
PBS_TOKEN_SECRET=MySecret
PROXMOX_HOST_2=https://pve4.example.com
PROXMOX_TOKEN_ID_2=pulse-monitor@pve!pulse
PROXMOX_TOKEN_SECRET_2=MySecret
PBS_HOST_2=https://pbs.example.com
PBS_NODE_NAME_2=pbs
PBS_TOKEN_ID_2=pulse-monitor@pbs!pulse
PBS_TOKEN_SECRET_2=MySecret

It works correctly for the PVE's; I can see data for both of them.
However, for the PBS tab, I only see two sub-tabs "pbs3-1" and "pbs", but no data.

![Image](https://github.com/user-attachments/assets/b943a778-8368-47ef-9073-59704624e03a)

When I modify the `.env` file to configure only one PBS instance, it functions correctly for that instance: the credentials are valid.
Where is the error?
Thanks for your help

**Comment by Anexgohan** [comment]
I have the same experience:  
![Image](https://github.com/user-attachments/assets/0827941d-4aee-4a2a-a974-f1237a16733d)

this is my `compose`:  
```
services:
  pulse-server:
    image: rcourtman/pulse:latest
    container_name: pulse
    ports:
      - "7655:7655"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - "const http = require('http'); const options = { hostname:
          'localhost', port: 7655, path: '/', method: 'GET' }; const
          req = http.request(options, (res) => { process.exit(res.statusCode >=
          200 && res.statusCode < 400 ? 0 : 1); }); req.on('error', () => {
          process.exit(1); }); req.end();"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 20s
```

this is my `.env`
```
# PVE 1:
PROXMOX_NODE_NAME=pve-shadow
PROXMOX_HOST=https://192.168.100.199:8006
PROXMOX_TOKEN_ID=monitor@pam!monitor-token
PROXMOX_TOKEN_SECRET=<redacted>

# PVE 2:
PROXMOX_NODE_NAME_2=pve-rpimox01
PROXMOX_HOST_2=https://192.168.100.198:8006
PROXMOX_TOKEN_ID_2=monitor@pam!monitor-token
PROXMOX_TOKEN_SECRET_2=<redacted>

# PBS 1:  
PBS_NODE_NAME=vm-pbs-shadow
PBS_HOST=https://192.168.100.189:8007
PBS_TOKEN_ID=monitor@pbs!monitor-token
PBS_TOKEN_SECRET=<redacted>

# PBS 2:  
PBS_NODE_NAME_2=vm-pbs-rpimox01
PBS_HOST_2=https://192.168.100.188:8007
PBS_TOKEN_ID_2=monitor@pbs!monitor-token
PBS_TOKEN_SECRET_2=<redacted>
```

If I remove the PBS number 2 from the `.env`, it shows up:  
![Image](https://github.com/user-attachments/assets/a0c5518b-c7d7-40a2-877b-c87b21a19f6f)

So, my guess is something is breaking the rendering of both together. as I can see in the docker logs when using both pbs1 and PBS2, the logs state successful connection:
```
pulse  |
pulse  | > pulse@3.7.0 start
pulse  | > node server/index.js
pulse  |
pulse  | INFO: Loaded configuration for 2 Proxmox endpoints.
pulse  | INFO: Found PBS configuration primary (API Token): vm-pbs-shadow (https://192.168.100.189:8007)
pulse  | INFO: Found PBS configuration 2 (API Token): vm-pbs-rpimox01 (https://192.168.100.188:8007)
pulse  | INFO: Loaded configuration for 2 PBS instances.
pulse  | INFO: Configuration loaded successfully.
pulse  | INFO: Using Metric Update Interval: 3000ms
pulse  | INFO: Using Discovery Update Interval: 30000ms
pulse  | INFO: Initializing API clients for 2 Proxmox VE endpoints...
pulse  | INFO: Initialized PVE API client for endpoint: pve-shadow (https://192.168.100.199:8006)
pulse  | INFO: Initialized PVE API client for endpoint: pve-rpimox01 (https://192.168.100.198:8006)
pulse  | INFO: Initializing API clients for 2 PBS instances...
pulse  | INFO: [PBS Init] Successfully initialized client for instance 'vm-pbs-shadow' (Token Auth)
pulse  | INFO: [PBS Init] Successfully initialized client for instance 'vm-pbs-rpimox01' (Token Auth)
pulse  | INFO: [PBS Init] Finished initialization. 2 / 2 PBS clients initialized successfully.
pulse  | INFO: All API clients initialized.
pulse  | [DataFetcher] Starting full discovery cycle...
pulse  | [DataFetcher] Fetching PVE discovery data for 2 endpoints...
pulse  | [DataFetcher] Fetching discovery data for 2 PBS instances...
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Starting fetch. Initial status: pending_initialization
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Determined nodeName: 'vm-pbs-shadow'. Configured nodeName: 'vm-pbs-shadow'
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Node name 'vm-pbs-shadow' is valid. Proceeding with data fetch.
pulse  | INFO: [DataFetcher] Fetching PBS datastore data for vm-pbs-shadow...
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Starting fetch. Initial status: pending_initialization
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Determined nodeName: 'vm-pbs-rpimox01'. Configured nodeName: 'vm-pbs-rpimox01'
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Node name 'vm-pbs-rpimox01' is valid. Proceeding with data fetch.
pulse  | INFO: [DataFetcher] Fetching PBS datastore data for vm-pbs-rpimox01...
pulse  | INFO: [DataFetcher] Fetched status for 1 PBS datastores via /status/datastore-usage for vm-pbs-shadow.
pulse  | INFO: [DataFetcher] Found 1 datastores for vm-pbs-shadow.
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Datastores and snapshots fetched. Number of datastores: 1
pulse  | INFO: [DataFetcher] Fetching PBS tasks for node vm-pbs-shadow on vm-pbs-shadow...
pulse  | INFO: [DataFetcher] Fetched status for 1 PBS datastores via /status/datastore-usage for vm-pbs-rpimox01.
pulse  | INFO: [DataFetcher] Found 1 datastores for vm-pbs-rpimox01.
pulse  | INFO: [DataFetcher] Fetched 50 tasks from PBS node vm-pbs-shadow.
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Tasks fetched. Result error: false, Tasks found: 50
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Processing tasks...
pulse  | INFO: [pbsUtils] Processed PBS Tasks - Backup: 2, Verify: 11, Sync: 0, Prune/GC: 6
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Tasks processed.
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Successfully fetched all data. Status set to: ok
pulse  | INFO: [DataFetcher - vm-pbs-shadow] Finalizing instance data. Status: ok, NodeName: vm-pbs-shadow
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Datastores and snapshots fetched. Number of datastores: 1
pulse  | INFO: [DataFetcher] Fetching PBS tasks for node vm-pbs-rpimox01 on vm-pbs-rpimox01...
pulse  | INFO: [DataFetcher] Fetched 50 tasks from PBS node vm-pbs-rpimox01.
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Tasks fetched. Result error: false, Tasks found: 50
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Processing tasks...
pulse  | INFO: [pbsUtils] Processed PBS Tasks - Backup: 21, Verify: 8, Sync: 0, Prune/GC: 3
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Tasks processed.
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Successfully fetched all data. Status set to: ok
pulse  | INFO: [DataFetcher - vm-pbs-rpimox01] Finalizing instance data. Status: ok, NodeName: vm-pbs-rpimox01
pulse  | [DataFetcher] Discovery cycle completed. Found: 2 PVE nodes, 8 VMs, 14 CTs, 2 PBS instances.
pulse  | [Discovery Cycle] Updated state. Nodes: 2, VMs: 8, CTs: 14, PBS: 2
pulse  | Server listening on port 7655
pulse  | Client connected
pulse  | Client connected
pulse  | Client requested data
```

**Comment by rcourtman** [comment]
Should be fixed in new release later today.

**Comment by rcourtman** [comment]
Try 3.8.0 and let me know if it's fixed. There's still work to do but hopefully it wont be blank.

**Comment by Anexgohan** [comment]
> Try 3.8.0 and let me know if it's fixed. There's still work to do but hopefully it wont be blank.

Works great,
![Image](https://github.com/user-attachments/assets/f26ce85e-43c8-4d8d-9dd9-c6265165da06)

Although I still cant figure out how to make the "Backups" tab work, as you can see the LATEST BACKUP, PBS INSTANCE, DATASTORE, # BACKUPS, 7-DAY HISTORY columns are all still empty.  
What am I doing wrong?  
![Image](https://github.com/user-attachments/assets/400f221e-f222-4698-a64c-d1a9edc9a4f3)

**Comment by Salan54** [comment]
Thanks for the fix. It works now : the PBS tabs content is visible for my two PBS.

**Comment by rcourtman** [comment]
@Anexgohan in the latest release 3.10.0, there's a diagnostic section that should help us see why the backups tab isnt populating. When you update to the latest version, if there are issues you will see a new icon in the top right which will take you to the diagnostics page. Or you can just navigate to http://your-pulse-host:7655/diagnostics.html

**Comment by cmar7945** [comment]
ran the diagnostics and im getting this:
[WARNING] PBS Permissions: PBS "pbs": Token can list datastores but not backup snapshots. This may affect backup overview functionality.
[WARNING] PBS Data: PBS is configured but no backups were found. Verify that backups exist in your PBS datastores and that the API token has permission to read them.
Followed the set up with the tokens having the Audit permission. Also added Datastore.Audit just in case but no change. Any help would be appreciated!

**Comment by cmar7945** [comment]
> ran the diagnostics and im getting this: [WARNING] PBS Permissions: PBS "pbs": Token can list datastores but not backup snapshots. This may affect backup overview functionality. [WARNING] PBS Data: PBS is configured but no backups were found. Verify that backups exist in your PBS datastores and that the API token has permission to read them. Followed the set up with the tokens having the Audit permission. Also added Datastore.Audit just in case but no change. Any help would be appreciated!

Corrected by adding a user permission of Audit and DatastoreReader

**Comment by Anexgohan** [comment]
I have "monitor" user and its token "monitor@pbs!monitor-token" as '/" audit and "/datastore" datastorereader
still the backup tab lists 0 backups

diagnostics page 

![Image](https://github.com/user-attachments/assets/1b01e4ee-3703-4a80-b2f4-23d9a98d4f3d)

**Comment by rcourtman** [comment]
Hi @Salan54\!  I have a couple of suggestions:

**Option 1: Test new feature branch**
I currently have a branch being tested that adds support for local PVE backups (not just PBS), which might resolve the backup visibility issues you're experiencing. If you're interested in testing, you can run the install script and select the `feature/pve-backups-support` branch when prompted.

**Option 2: Better diagnostics**
To help troubleshoot your current setup, could you please use the "📋 Copy Safe Report" button on the diagnostics page and paste the actual diagnostic text here? The text format gives me much more detail to work with than screenshots and will help identify the exact issue with your PBS configuration.

Either approach should help us get to the bottom of this

**Comment by Salan54** [comment]
Hi @rcourtman . Thanks again for this great app and your quick fixes.
I currently use v3.11.1 on docker :
- I can see the data for my two PBSs. The problem is now fixed.
- I have the same problem as @Anexgohan regarding the backups tab : I only have data for the first backup (domoticz). For all the other, I have N/A...

![Image](https://github.com/user-attachments/assets/e472615c-36f2-44ba-aa63-5048e4dc2744)

You will find enclosed the  safe diagnostic file for my installation.

**removed**

I hope you will be able to fix this issue. Thanks again

**Comment by Anexgohan** [comment]
here's my safe report:
[pulse_diagnostics_2025-05-28T20-05-26.json](https://github.com/user-attachments/files/20494501/pulse_diagnostics_2025-05-28T20-05-26.json)

I have 0 PVE backups ,  
I switched away from vzdumps since i got burned by them, they are not real backups and can show you 100% healthy with 100% corrupted data in them, no one should ever use them.   
Use PBS thats real backup

**Comment by rcourtman** [comment]
@Salan54 Please try updating to 3.12.3, and check the readme again for permissions on the PBS token. It's been updated to reflect that the token needs correct user permissions. Let me know if you still have probs

**Comment by Salan54** [comment]
Hello @rcourtman , thanks for your help.
I now run v3.15.1 but I still have problems regarding the Backups tab.
Here is a capture filtered on PVE3 :

![Image](https://github.com/user-attachments/assets/f9ac54c5-3ff4-4159-8dc1-65a7e4ccc4fa)

As you can see, no backups are visible "No backups found"
Here are the permissions for user and API token :

![Image](https://github.com/user-attachments/assets/b6ec5be4-06a1-45f3-bed0-0a82314bd202)

And here is the backups tab on the PVE. As you can see, I have backups configured locally (QNAP NAS), on the local PBS (pbs3-1) and on a remote pbs (pbs-dakhla). But they don't reflect on the pulse backups tab...

![Image](https://github.com/user-attachments/assets/33dd11f1-630b-4ac7-a85d-1b952d738d39)

You will find enclosed the pulse_diagnostics.json file.
**Removed**
Let me know if you need anything else

**Comment by rcourtman** [comment]
Thank you for providing the diagnostic report. I noticed the sanitization wasn't working properly - some hostnames and IPs were still visible. I've just pushed a fix (commit 7abe322) that properly sanitizes all sensitive fields. This will be included in the next patch release.

For your privacy, you may want to edit your comment to remove the diagnostic data now that I've seen it. The information exposed (internal IPs and hostnames) is relatively low-risk, but it's still better to keep private.

Regarding your original issue - looking at the diagnostics, your configuration appears correct. The issue might be timing-related. Could you try running the diagnostics again after Pulse has been running for a few minutes?

**Comment by Anexgohan** [comment]
just a guess,  
but is this issue of empty backups caused when using a deeper Namespace in PBS:
for example my pbs structure has <pve-name>/containers, <pve-name>/node and <pve-name>/custom    

due to this the backup structure inside PBS shows up as:  

![Image](https://github.com/user-attachments/assets/faa2e327-f655-4012-9ac7-27e4813e08b5)
![Image](https://github.com/user-attachments/assets/e631e2ba-f969-4e31-a4ae-52ff44b60075)

**Comment by Anexgohan** [comment]
Here is another observation, 
even the PBS tab does not show any backup tasks:  

![Image](https://github.com/user-attachments/assets/a8314a2d-c872-4453-be17-717ec10831ca)
![Image](https://github.com/user-attachments/assets/53c42ee6-e60a-4548-8f90-59e9148fdd43)

**Comment by Anexgohan** [comment]
does it work now, asking cause i don't want to upgrade and break my current setup.

**Comment by rcourtman** [comment]
@Anexgohan Namespace support is much more fleshed out and supported than before in the latest version. I would encourage you to try the latest RC release https://github.com/rcourtman/Pulse/releases/tag/v3.30.0-rc3

It's working well for me. 

![Image](https://github.com/user-attachments/assets/3393d459-a845-49b7-95d1-207308bf1d03)

**Comment by Anexgohan** [comment]
> [@Anexgohan](https://github.com/Anexgohan) Namespace support is much more fleshed out and supported than before in the latest version. I would encourage you to try the latest RC release https://github.com/rcourtman/Pulse/releases/tag/v3.30.0-rc3


thanks for responding, I tried the v[3.30.0-rc3]  
but sadly the backups still don't show up

![Image](https://github.com/user-attachments/assets/d4a300e8-4204-4f3b-af64-3fe0df0b7381)
Also, why is it picking up 30 day old failures, can I set this to limit it to last 7days only?  
![Image](https://github.com/user-attachments/assets/47a6a106-d04c-447a-94ad-5eef01872b1e)
![Image](https://github.com/user-attachments/assets/08f2abc7-f592-4f97-b486-e6502a94f83e)

Also, attaching a safe Diagnostic report just in case, all permission are set ok

[pulse_diagnostics_2025-06-16T17-53-54.json](https://github.com/user-attachments/files/20762279/pulse_diagnostics_2025-06-16T17-53-54.json)

**Comment by rcourtman** [comment]
PBS support has been redesigned in recent versions. Can you try [v3.31.0](https://github.com/rcourtman/Pulse/releases/tag/v3.31.0)? 

Multiple PBS instances should work but I haven't extensively tested this specific configuration. If you still have issues with multiple PBS instances, please let me know and I'll investigate further.

**Comment by Anexgohan** [comment]
> PBS support has been redesigned in recent versions. Can you try [v3.31.0](https://github.com/rcourtman/Pulse/releases/tag/v3.31.0)?
> 
> Multiple PBS instances should work but I haven't extensively tested this specific configuration. If you still have issues with multiple PBS instances, please let me know and I'll investigate further.

Cheers, I can see the numbers in the Backups tab finally, but now a more serious issue, I can't see actual VM's in the main tab, I have made a separate issue for it. for now reverting back

**Comment by rcourtman** [comment]
v3.32.0 has improvements for PBS instance filtering. Can you try the latest version? If data still doesn't load, please share the diagnostics output.

**Comment by rcourtman** [comment]
Thanks for the report. The PBS integration has been improved in v3.33.0-rc1 with better deduplication display and data handling. Can you try the latest version to see if your multiple PBS instances now load data correctly?

**Comment by rcourtman** [comment]
Closing as stale. This issue is from 6+ months ago and relates to older versions. Please upgrade to v4.1.8 and reopen if you're still experiencing PBS issues with multiple instances.

**Comment by rcourtman** [comment]
Reopening

**Comment by rcourtman** [comment]
Thanks for the report. Closing since triage-complete with no updates for 66 days.
