### ISSUE TITLE
Incorrect backup status for container list

### ISSUE THREAD

**Issue by devachnid** [rcourtman/Pulse#786]
**Describe the bug**
All my CTs and VMs have multiple backups: on the host, and on 2 PBSs, however on the server overview page they are all showing the grey 'No backup found' icon.

**To Reproduce**
1. Go to Backups -> all backups visible
2. Go To Overview -> all CTs/VMs show 'No backup found'

**Expected behavior**
Correct backup status

**Environment:**
 - Pulse Version: v4.35.0
 - Installation Type: ProxmoxVE LXC

**Additional context**

<img width="1397" height="510" alt="Image" src="https://github.com/user-attachments/assets/9e346dcd-bb7a-4d94-b728-cb8600d54bba" />

<img width="135" height="575" alt="Image" src="https://github.com/user-attachments/assets/af1eea34-daf8-4ed3-983c-e32346d49c0b" />

<img width="1229" height="648" alt="Image" src="https://github.com/user-attachments/assets/4712bd3f-98fe-49e4-9a5f-f3a2cd2e3f6e" />

[pulse-diagnostics-sanitized-2025-11-30.json](https://github.com/user-attachments/files/23842338/pulse-diagnostics-sanitized-2025-11-30.json)

**Comment by rcourtman** [comment]
This is a bug - the backup status indicator was added to the UI but the backend isn't populating the `lastBackup` field on guests from actual backup data.

The indicator works correctly in demo mode (which uses mock data with populated `lastBackup`), but in production the field is always empty because the real backup data isn't being joined to guest objects.

Investigating the fix - it requires matching guests to their storage backups by VMID and finding the most recent backup timestamp.

**Comment by rcourtman** [comment]
Fixed in 54fab46b. The backup status indicator will now show correctly by syncing the latest backup timestamp to each guest after backup polling completes.

This will be in the next release.

**Comment by darthrater78** [comment]
<img width="293" height="114" alt="Image" src="https://github.com/user-attachments/assets/855d4d7f-e6e9-43a1-a37a-7c3f0d88300f" />

I'm still not seeing backups badge correctly

**Comment by rcourtman** [comment]
@darthrater78 You're on v4.36.0 which has the initial backup indicator fix (54fab46b), but there was a follow-up issue discovered: the backup timestamp was being reset every time VMs/containers were polled (which happens more frequently than backup polling).

The fix for that (8597eca0) was committed after v4.36.0 and will be in the next release. It preserves the `LastBackup` field when guest data is refreshed.

In the meantime, you can verify the backup data is being collected correctly by checking:
- Go to Backups page - you should see all your backups listed there
- The issue is just the indicator on the Overview/Dashboard not displaying correctly

Will be resolved in the next release.

**Comment by rcourtman** [comment]
Fixed in v4.36.0 and later releases.

The two commits that addressed this:
- 54fab46b - Initial fix to sync backup timestamps to guests
- 8597eca0 - Follow-up to preserve LastBackup field when guest data refreshes

If you're still seeing issues on v4.36.2 or later, please open a new issue.
