### ISSUE TITLE
Memory doesn't appear to be graphing correctly

### ISSUE THREAD

**Issue by RLSinRFV** [rcourtman/Pulse#788]
See image

<img width="565" height="656" alt="Image" src="https://github.com/user-attachments/assets/e9430c08-5157-457a-8c9f-f038ceb6ac4d" />

**Comment by rcourtman** [comment]
Sorry about the earlier confusion - I should have spotted the obvious issue in your screenshot straight away. The memory bars at 37% and 41% were clearly showing as completely full when they should be less than half.

Fixed in 32ffc104. The bars were using flex layout which caused them to grow beyond their percentage width. Changed to absolute positioning so the widths scale correctly.

This will be in the next release.

**Comment by ZaDarkSide** [comment]
Issue still persists in Proxmox Overview for Memory bar for VMs in new release [v4.36.0](https://github.com/rcourtman/Pulse/releases/tag/v4.36.0)

<img width="1511" height="917" alt="Image" src="https://github.com/user-attachments/assets/5ffe63d3-3267-460e-848e-8914d2bf4852" />

**Comment by rcourtman** [comment]
Found the root cause. The previous fix addressed flex layout, but the actual bug was in the balloon calculation logic.

When Proxmox has ballooning configured but set to maxmem (effectively no ballooning), the component was calculating:
- `active = used - balloon = used - total` → 0 (clamped)
- `balloonPercent = total / total * 100` → 100%

This caused the bar to always show 100% yellow regardless of actual memory usage.

Fixed in aec63b7a - now only shows balloon segment when actual ballooning is in effect (`balloon > 0 && balloon < total`). Without active ballooning, it correctly shows used memory as green with the actual percentage.

This will be in the next release.

**Comment by RLSinRFV** [comment]
Thank you for the thorough explanation @rcourtman

**Comment by rcourtman** [comment]
The balloon calculation fix (aec63b7a) will be in the next release. Thanks for reporting this and confirming the issue.
