### ISSUE TITLE
Guest URLs in PVE settings not used

### ISSUE THREAD

**Issue by MichiFr** [rcourtman/Pulse#870]
**Describe the bug**
I've setup a guest URL for my PVE nodes. Nevertheless, when clicking in the appropriate node name, the host URL is used.

**Expected behavior**
I expected the guest URL to be called.

**Environment:**
 - Pulse Version: 5.0.0 RC4
 - Installation Type: Docker

The same applies to the PBS settings, too!

**Comment by rcourtman** [comment]
Fixed in commit 16b383ce.

**Changes:**
- PVE nodes: Fixed `buildNodeUrl` in the Alerts section to prioritize `guestURL` over `host` (was ignoring it entirely)
- PBS nodes: Added full Guest URL support (config, API, model, and UI navigation)
- PMG nodes: Added full Guest URL support (config, API, model, and UI navigation)

The Guest URL setting now works correctly for all node types. When configured, it takes priority over the Host URL when clicking on node names to navigate to the Proxmox/PBS/PMG web UI.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by MichiFr** [comment]
Should this be fixed/implemented in 5.0.3?
Just updated, but still the Guest URL is not used ending in a call to the Host URL.

**Comment by rcourtman** [comment]
The Guest URL fix in 5.0.3 only covered part of the UI. There was another location (`ThresholdsTable.tsx`) that was still using the host URL directly.

Fixed in commit 780a9b65. The ThresholdsTable now prioritizes `guestURL` over `host` for node navigation links, matching the behavior of other components.

This will be available in the next release (5.0.4).

**Comment by MichiFr** [comment]
> This will be available in the next release (5.0.4).

Sorry for posting again, but after installing 5.0.5 now, the issue still persists. When clicking on any of those marked nodes, a new tab opens using the host url, not the guest. Others show the same behaviour.

<img width="1366" height="903" alt="Image" src="https://github.com/user-attachments/assets/b41a9dcd-e097-4cc9-aa8d-dc9d041a5648" />
