### ISSUE TITLE
Proxmox hosts with the same hostname don't work

### ISSUE THREAD

**Issue by rallisf1** [rcourtman/Pulse#891]
**Describe the bug**
When adding 2 hosts that have the same hostname the following happens:

Only 1 record is shown in Settings -> Proxmox

<img width="950" height="240" alt="Image" src="https://github.com/user-attachments/assets/c013f89d-d6d6-49d0-84e6-6e74ed384fd0" />

There are 2 tokens in the Token Inventory

<img width="946" height="328" alt="Image" src="https://github.com/user-attachments/assets/cfb264ff-ba47-4ee2-b91a-33f5de1c6647" />

There are 2 hosts shown in Hosts

<img width="1303" height="96" alt="Image" src="https://github.com/user-attachments/assets/277a9dd8-93c4-4afe-bb74-467373de423a" />

Proxmox Monitoring is broken

<img width="1351" height="636" alt="Image" src="https://github.com/user-attachments/assets/2883a7ff-e5d3-4615-87c7-89c9d4a59316" />

**To Reproduce**
1. Set up 2 Proxmox hosts with the same hostname
2. Add them to Pulse using the Pulse agent

**Expected behavior**
Both should work and IMO I should be able to rename them in Pulse, not just set their management urls.

**Environment:**
 - Pulse Version: 5.0.1
 - Installation Type: Docker

**Additional context**

Using hostnames as database IDs is really bad...

Diagnostics:

```json
{
  "version": "5.0.1",
  "runtime": "go",
  "uptime": 796.677692862,
  "nodes": [
    {
      "id": "px1",
      "name": "px1",
      "host": "https://10.0.2.224:8006",
      "type": "pve",
      "authMethod": "api_token",
      "connected": false,
      "error": "Failed to connect to Proxmox API: authentication error: API error 401 (Unauthorized): Invalid credentials or token"
    }
  ],
  "pbs": null,
  "system": {
    "os": "linux",
    "arch": "arm64",
    "goVersion": "go1.24.11",
    "numCPU": 12,
    "numGoroutine": 74,
    "memoryMB": 36
  },
  "discovery": {
    "enabled": false,
    "configuredSubnet": "auto",
    "environmentOverride": "auto",
    "subnetAllowlist": [],
    "subnetBlocklist": [
      "169.254.0.0/16"
    ],
    "scanning": false
  },
  "apiTokens": {
    "enabled": true,
    "tokenCount": 4,
    "hasEnvTokens": false,
    "hasLegacyToken": false,
    "recommendTokenSetup": false,
    "recommendTokenRotation": false,
    "tokens": [
      {
        "id": "a241ec88-8df4-49bd-af41-b712b0d76a00",
        "name": "proxmox-agent-pve-1766590273",
        "hint": "d9f6d7…c814",
        "createdAt": "2025-12-24T15:31:13Z",
        "lastUsedAt": "2025-12-24T15:44:58Z",
        "source": "user"
      },
      {
        "id": "ba68b731-9cca-454a-9b2b-1756e554763f",
        "name": "monitor",
        "hint": "cb70c5…123b",
        "createdAt": "2025-12-24T13:24:37Z",
        "lastUsedAt": "2025-12-24T15:45:05Z",
        "source": "user"
      },
      {
        "id": "c9c2a8b7-3b6f-4b1c-9294-956dae30b13f",
        "name": "coolify",
        "hint": "58e901…5fa8",
        "createdAt": "2025-12-24T13:20:17Z",
        "lastUsedAt": "2025-12-24T15:44:47Z",
        "source": "user"
      },
      {
        "id": "47c70a94-572a-49f6-b77b-26cd6b0a8aa5",
        "name": "proxmox-agent-pve-1766582237",
        "hint": "c45705…d601",
        "createdAt": "2025-12-24T13:17:17Z",
        "lastUsedAt": "2025-12-24T15:45:10Z",
        "source": "user"
      }
    ],
    "usage": [
      {
        "tokenId": "ba68b731-9cca-454a-9b2b-1756e554763f",
        "hostCount": 1,
        "hosts": [
          "v2202506191128348547"
        ]
      },
      {
        "tokenId": "c9c2a8b7-3b6f-4b1c-9294-956dae30b13f",
        "hostCount": 1,
        "hosts": [
          "cool"
        ]
      }
    ]
  },
  "dockerAgents": {
    "hostsTotal": 2,
    "hostsOnline": 2,
    "hostsReportingVersion": 2,
    "hostsWithTokenBinding": 2,
    "hostsWithoutTokenBinding": 0,
    "hostsNeedingAttention": 0,
    "recommendedAgentVersion": "v5.0.1",
    "notes": [
      "All Docker agents are reporting with dedicated tokens and the expected version."
    ]
  },
  "alerts": {
    "legacyThresholdsDetected": false,
    "legacyScheduleSettings": [
      "timeThreshold"
    ],
    "missingCooldown": true,
    "missingGroupingWindow": true,
    "notes": [
      "Global alert delay still uses the legacy timeThreshold setting. Save the alerts configuration to migrate to per-metric delays.",
      "Alert cooldown is not configured. Set a cooldown under Settings → Alerts → Schedule to prevent alert storms.",
      "Alert grouping window is disabled. Configure a grouping window to bundle related alerts."
    ]
  },
  "errors": []
}
```

**Comment by rcourtman** [comment]
Fixed in 72c05acd. 

The issue was that auto-registration matched nodes by hostname (not just host URL), so when two hosts shared the same hostname like `px1`, the second would overwrite the first.

Changes:
- Auto-registration now matches by host URL only (not name)
- When duplicate hostnames are detected, they're disambiguated with their IP: `px1` and `px1 (10.0.2.224)`

To fix your setup: remove both nodes from Pulse and re-run the agent setup on each. They'll now register as separate nodes.

This was a recurring issue - added regression tests to prevent it from happening again.

**Comment by rallisf1** [comment]
Some small bugs remain.

1. In Alerts -> Thresholds ->  VMs & Containers: it shows both hosts' containers/vms under the same host.
2. In Proxmox -> Overview (node list): although it shows both hosts the temp reading in both is from the host that got added last. In Hosts the readings are correct.
3. In Settings -> Agents -> Managed Agents: it only shows 1 agent instead of 2

Also in many places it displays the hostname, instead of the node name.

**Comment by rcourtman** [comment]
Fixed the VMs grouped under same host issue in a1eb9cf1.

The frontend was grouping VMs by `node` (raw hostname) instead of `instance` (disambiguated name). Now VMs from "px1" and "px1 (10.0.2.224)" will display in separate groups.

**Important**: For this fix to take effect, the nodes need to be re-registered with different names. In Settings → Proxmox, delete both nodes with the same hostname and re-add them. The second should automatically become "px1 (10.0.2.224)".

Still investigating items 2 and 3 (temperature readings and managed agents display).

**Comment by rcourtman** [comment]
### Update: Fixed 2 of 3 reported issues

**Fixed in this session:**
1. ✅ **VMs grouped under same host** - Fixed in a1eb9cf1 (group by instance, not node)
2. ✅ **Managed Agents showing only 1** - Fixed in 61b69fe2 (key by id, not hostname)

**Still investigating:**
3. ⏳ **Temperature readings mixed up** - This requires more investigation into the backend temperature collection and association logic.

**Required action from your side:**
For fixes 1 and 2 to take effect, please **delete and re-add both hosts** with the duplicate hostname in Settings → Proxmox. The second host should automatically get a disambiguated name like "px1 (10.0.2.224)".

Will open a separate issue for the temperature investigation if needed.

**Comment by rallisf1** [comment]
I hate to spam, but kudos for real! I wouldn't expect such fast responses; let alone fixes even if I paid for it.

Btw feel free to take your time. It's Xmas!

**Comment by rcourtman** [comment]
All reported issues now fixed:

1. ✅ **VMs grouped under same host** - Fixed in a1eb9cf1
2. ✅ **Managed Agents showing only 1** - Fixed in 61b69fe2  
3. ✅ **Temperature readings mixed up** - Fixed in ea0fafd5

The temperature bug was caused by the host agent temperature lookup matching by hostname alone. When two nodes had the same hostname (e.g., 'px1'), it would always return temperature from whichever host agent appeared first.

The fix now uses the unique node ID (via LinkedNodeID) for matching, which correctly distinguishes between nodes even when they share hostnames.

**Required action:** Delete and re-add both hosts with duplicate hostnames in Settings → Proxmox. The second should get a disambiguated name like 'px1 (10.0.2.224)'.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by rallisf1** [comment]
@rcourtman  After upgrading to version 6, this is again an issue.
