### ISSUE TITLE
Incorrect information on Backups tab

### ISSUE THREAD

**Issue by adm2k** [rcourtman/Pulse#895]
Not sure if this is a bug or just me missing something. On the backup tab there is a  "snapshot" entry that did exist for the VM but has since been deleted. Also, I created another "snapshot" on another VM and it is not displaying.

I have tried refreshing etc. Anything else I should look at?

This image is the one that no longer exists:

<img width="1201" height="54" alt="Image" src="https://github.com/user-attachments/assets/e256d070-8145-452b-8913-2f78339a691b" />

**Comment by adm2k** [comment]
Version 5.0.1

One was created several hours ago and deleted about 20 minutes ago
The other was created about 15 minutes ago.

journalctl -u pulse.service --since "5 minutes ago" | grep -i snapshot
Returns nothing...

**Comment by krestaino** [comment]
I've noticed this too. However, after some time, hours perhaps, the info does populate. In my screenshot, you can see missing info for LXC 153 and 151 and then VM 142. Eventually, at some point today, it will populate with the correct data. I noticed this same behavior yesterday with other random backups, that are now all populated today. I'm on Pulse 5.0.2.

<img width="1398" height="681" alt="Image" src="https://github.com/user-attachments/assets/0a77ec6e-5f51-4924-aae3-169905030be5" />

```
admin@pulse ~> sudo journalctl -u pulse.service --since "5 minutes ago" | grep -i snapshot
Dec 24 15:16:28 pulse pulse[135106]: {"level":"info","component":"pulse-config","instance":"nuc","duration":43272.173809,"time":"2025-12-24T15:16:28-05:00","message":"Completed background backup/snapshot polling"}
Dec 24 15:17:23 pulse pulse[135106]: {"level":"info","component":"pulse-config","instance":"nuc","timeout":130000,"time":"2025-12-24T15:17:23-05:00","message":"Starting background backupsnapshot polling"}
Dec 24 15:17:38 pulse pulse[135106]: {"level":"info","component":"pulse-config","instance":"nuc","duration":14654.546875,"time":"2025-12-24T15:17:38-05:00","message":"Completed background backup/snapshot polling"}
Dec 24 15:20:43 pulse pulse[135106]: {"level":"info","component":"pulse-config","instance":"nuc","timeout":130000,"time":"2025-12-24T15:20:43-05:00","message":"Starting background backupsnapshot polling"}
admin@pulse ~>
```

**Comment by rcourtman** [comment]
Fixed in commit 08e9202b. Backup/snapshot data now broadcasts immediately after polling completes instead of waiting for the next scheduled broadcast interval.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by adm2k** [comment]
I am on version 5.0.5 but still having the same issue here with snapshots clearing out once they have actually been removed.

<img width="948" height="209" alt="Image" src="https://github.com/user-attachments/assets/d0466dd7-d6f7-46a4-8c38-ab82a45c26f9" />

Am I missing something?

Many thanks for this great tool!

**Comment by rcourtman** [comment]
Looking at the latest comment - you mentioned deleted snapshots not clearing out.

A few questions to diagnose:

1. After deleting the snapshot in Proxmox, how long did you wait before checking Pulse? Backup/snapshot polling runs every few minutes.
2. Did you check if the snapshot page shows "Updated X ago" at the top? This confirms when the last poll completed.
3. Does the problem persist after restarting the Pulse container/service?
4. In your Pulse logs (`journalctl -u pulse.service --since "10 minutes ago" | grep -i snapshot`), do you see any timeout or error messages?

The prior fix (08e9202b) addressed the delay in broadcasting new data, but if there's a polling timeout or error, stale data might be retained. The screenshot shows snapshots with "2 days, 1 hour old" - are these the ones that should be deleted?

**Comment by adm2k** [comment]
See my responses (in blood italics) especially question 3

1 After deleting the snapshot in Proxmox, how long did you wait before checking Pulse? Backup/snapshot polling runs every few minutes. **_3 to 4 minutes_**

2 Did you check if the snapshot page shows "Updated X ago" at the top? This confirms when the last poll completed. **_Yes_**

3 Does the problem persist after restarting the Pulse container/service? **_This resolved the issue_**

4 In your Pulse logs (journalctl -u pulse.service --since "10 minutes ago" | grep -i snapshot), do you see any timeout or error messages? **_No error messages_**

**Comment by adm2k** [comment]
Any thoughts on this issue?

**Comment by adm2k** [comment]
I have Pulse Pulse installed as a systemd service 

This is the only way new or removed snapshots etc. are updated - running this...

systemctl restart pulse
