### ISSUE TITLE
Agent installation, installation command fails on pve node

### ISSUE THREAD

**Issue by MichiFr** [rcourtman/Pulse#909]
**Describe the bug**
When creating an agent installation command, the command fails when executed on the PVE node.

This command is automatically created in Pulse UI:
`curl -fsSL http://192.168.0.10:7655/install.sh | sudo bash -s -- --url http://192.168.0.10:7655 --token 97309422923ee25c07d50ba7fabed2459099a93a67efcf481243df5ee451c935 --interval 30s`

Results in:
`-bash: sudo: command not found
curl: (23) Failure writing output to destination, passed 7240 returned 800`

**Environment:**
 - Pulse Version: 5.0.3
 - Installation Type: Docker

**Additional context**
Logged into PVE with root in SSH terminal.
Dropping sudo from command line fixed the issue, btw.

**Comment by MichiFr** [comment]
I see no temperatures in storage and hosts, is this due to smartctl is missing on appropriate hosts or because I've removed sudo in above command to get the agent installed? I'm running an agent in all nodes and docker hosts.

<img width="1366" height="635" alt="Image" src="https://github.com/user-attachments/assets/34463ed1-2a21-4e9b-8e62-5af594ece650" />

<img width="1366" height="507" alt="Image" src="https://github.com/user-attachments/assets/2ea430a3-c8f8-4879-95f8-9da1b3653359" />

**Comment by rcourtman** [comment]
Fixed in main. The install command no longer includes `sudo` - the script checks for root privileges and will prompt if not running as root.

**For the installation issue:** Drop `sudo` or run as root via `su -`. This is now fixed in the next release.

**For the missing temperatures:** This is expected - S.M.A.R.T. temperature readings require `smartctl` to be installed on the host. Install it with:
```bash
apt install smartmontools
```
Then restart the agent. The agent needs root/sudo privileges to read S.M.A.R.T. data, so if you installed without sudo, ensure the agent is still running as root (which it should be on Proxmox).

**Comment by MichiFr** [comment]
Thanks for your prompt reply. 
smartmontools are already installed on all of my nodes since the intial setup, the agent was installed, using above command just before.

Nevertheless, there are no temps showing up in Pulse. Neither for CPU nor for harddisks and nVMEs. OK, later may not show any temps if not supported.

Anyway, I just executed `smartctl -a /dev/nvme0n1` in one of the nodes and got those information amongst others.

`SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        42 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    1%
Data Units Read:                    50,346,942 [25.7 TB]
Data Units Written:                 40,887,453 [20.9 TB]
Host Read Commands:                 907,833,098
Host Write Commands:                689,430,742
Controller Busy Time:               3,259
Power Cycles:                       2,291
Power On Hours:                     8,037
Unsafe Shutdowns:                   108
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    92
Critical Comp. Temperature Time:    31
Temperature Sensor 1:               56 Celsius
Temperature Sensor 2:               39 Celsius

Error Information (NVMe Log 0x01, 16 of 256 entries)
No Errors Logged`

So, temps are available, Pulse is missing them:

<img width="1366" height="608" alt="Image" src="https://github.com/user-attachments/assets/e72ce64e-8aed-4f84-97f2-9fb8def739fd" />

**Comment by rcourtman** [comment]
The screenshots show the agent is reporting (you have entries in Hosts), but no temperature data is coming through.

Key question: where did you install the agent? If it's inside an LXC container, it can't access the host's physical disks or sensors - those are isolated by the container.

**For Proxmox nodes:** Install the agent directly on each PVE host, not inside a container:
```bash
ssh root@your-pve-node
curl -fsSL https://pulserelay.pro/install-agent.sh | sh -s -- --url http://pulse:7655 --token YOUR_TOKEN
```

**To verify the agent sees the disks:** SSH to the PVE node where you ran `smartctl` manually and check:
```bash
/opt/pulse-agent/pulse-agent --run-once --log-level=debug 2>&1 | grep -i "smart\|disk"
```

If it shows "Collected S.M.A.R.T. disk data", the agent is working - the issue would be on the display side.

**Comment by tonydlo** [comment]
I was having a similar issue, but I just followed your instructions to install the agent directly on the proxmox host after installing pulse the default way, and suddenly I'm getting temperature readings now!!!

However, the dashboard now has a duplicate entry for my proxmox host in the Proxmox tab (the second one includes an IP address), but in the Hosts tab it only shows one. Was there a different way I should have installed this? Otherwise, how can I properly clean up the duplicate - should I go to Settings and delete the one that doesn't say "Agent"?

**Comment by MichiFr** [comment]
The agents on each PVE were installed in a SSH session, with above command dropping the sudo part of it.

The command `/opt/pulse-agent/pulse-agent --run-once --log-level=debug 2>&1 | grep -i "smart\|disk"` gets executed, however no single line was output.

I've shorten the command to `/opt/pulse-agent/pulse-agent --run-once --log-level=debug 2
-bash: /opt/pulse-agent/pulse-agent: No such file or directory`
But this fails somehow as you can see above.

Folder /opt does not contain any files or subfolders, btw. So no agent files either. However, Pulse gets some data from the nodes since installing the agents, hence something is going on. Maybe a different installation path was used?

**Edit**: pulse agent is installed here:
`which pulse-agent

/usr/local/bin/pulse-agent`

Now executed 
`/usr/local/bin/pulse-agent --run-once --log-level=debug 2>&1 | grep -i "smart\|disk"`

Results in
`  -disk-exclude value
        Mount point or path prefix to exclude from disk monitoring (repeatable)`

**Comment by rcourtman** [comment]
**@tonydlo**: That duplicate is expected when installing the agent on an existing Proxmox node. To clean up, go to Settings → Managed Agents and delete the entry without the "Agent" badge.

**@MichiFr**: The previous debug command was incomplete - `--run-once` needs `--url` and `--token` to actually execute, which is why you only saw help text (the grep caught the `-disk-exclude` flag description).

Try these instead:

1. **Check agent version**:
   ```bash
   pulse-agent --version
   ```
   S.M.A.R.T. collection requires v5.0.3+. Temperature sensors require v5.0.0+.

2. **Check service logs** (this shows what the running agent is actually doing):
   ```bash
   journalctl -u pulse-agent -n 100 --no-pager
   ```
   Look for any "SMART", "sensor", or error messages.

3. **Verify lm-sensors is installed** (for CPU temps):
   ```bash
   sensors
   ```

4. **Verify Pulse server version**: The agent binary is downloaded from your Pulse server, so if your Docker container is on an older version, you'll get an older agent. Check your Pulse version in Settings → About, update if needed, then reinstall the agent.

**Comment by MichiFr** [comment]
Agent version shows `v5.0.3`

Command journalctl shows no signs of smart or sensor errors:
`journalctl -u pulse-agent -n 100 --no-pager
Dec 25 17:38:14 elbe systemd[1]: Started pulse-agent.service - Pulse Unified Agent.
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","version":"v5.0.3","pulse_url":"http://192.168.0.10:7655","host_agent":true,"docker_agent":false,"kubernetes_agent":false,"proxmox_mode":true,"auto_update":true,"time":"2025-12-25T17:38:14+01:00","message":"Starting Pulse Unified Agent"}
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","addr":":9191","time":"2025-12-25T17:38:14+01:00","message":"Health/metrics server listening"}
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","time":"2025-12-25T17:38:14+01:00","message":"Command execution disabled (use --enable-commands to enable)"}
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","time":"2025-12-25T17:38:14+01:00","message":"Host agent module started"}
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","time":"2025-12-25T17:38:14+01:00","message":"Proxmox mode enabled, checking setup..."}
Dec 25 17:38:14 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","type":"pve","time":"2025-12-25T17:38:14+01:00","message":"Auto-detected Proxmox type"}
Dec 25 17:38:15 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","token_id":"pulse-monitor@pam!pulse-1766680694","time":"2025-12-25T17:38:15+01:00","message":"Created Proxmox API token"}
Dec 25 17:38:15 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","host":"https://192.168.0.9:8006","time":"2025-12-25T17:38:15+01:00","message":"Successfully registered Proxmox node with Pulse"}
Dec 25 17:38:15 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","type":"pve","host":"https://192.168.0.9:8006","token_id":"pulse-monitor@pam!pulse-1766680694","time":"2025-12-25T17:38:15+01:00","message":"Proxmox node registered successfully"}
Dec 25 17:41:46 elbe pulse-agent[3981223]: {"level":"info","component":"host-agent","time":"2025-12-25T17:41:46+01:00","message":"Server enabled command execution - starting command client"}
Dec 25 17:41:46 elbe pulse-agent[3981223]: {"level":"info","component":"command-client","time":"2025-12-25T17:41:46+01:00","message":"Connected and registered with Pulse command server"}`

Both agent and Pulse are on the same version: 5.0.3

Sensors are not installed. Did that now with `apt install lm-sensors` and the hosts are now showing up temps, the pyhsical disks are still missing temp values.

**Comment by tonydlo** [comment]
@rcourtman thanks, I deleted the non-agent and things look good now.

I don't want to further diverge this thread, so just wondering if I should open a feature request to create alerts for physical disk storage temperatures? I have some drives that I want to keep an eye on because ventilation isn't perfect.

Thanks for all your help.

**Comment by MichiFr** [comment]
> systemctl stop pulse-agent
> pulse-agent --log-level=debug --run-once 2>&1 | grep -i "smart\|block\|disk"

Gives me this output, nothjng fancy 😌
`# pulse-agent --log-level=debug --run-once 2>&1 | grep -i "smart\|block\|disk"
  -disk-exclude value
        Mount point or path prefix to exclude from disk monitoring (repeatable)`


> Also verify smartctl is in PATH for the service:
> 
> which smartctl

Can be found here
`# which smartctl
/usr/sbin/smartctl`


> If you're not seeing any output from the grep, that likely means SMART collection is being skipped entirely - post the full `--run-once` output and I'll take a look.

No matter if I execute `pulse-agent --log-level=debug --run-once 2 ` or `pulse-agent --log-level=debug --run-once` or even `pulse-agent --log-level=debug` I always get the help of pluse-agent, e.g.:
`pulse-agent --log-level=debug --run-once 
flag provided but not defined: -run-once
Usage of pulse-agent:
  -agent-id string
        Override agent identifier
  -disable-auto-update
        Disable automatic updates
  -disable-commands
        [DEPRECATED] Commands are now disabled by default; use --enable-commands to enable
  -disk-exclude value
        Mount point or path prefix to exclude from disk monitoring (repeatable)
....`

So, what is the correct syntax here to get the full debug output?

**Comment by rcourtman** [comment]
Apologies for the confusion — there's no `--run-once` flag. That was incorrect.

To debug S.M.A.R.T. collection, temporarily enable debug logging in the running agent:

1. Edit the service:
   ```bash
   sudo systemctl edit pulse-agent
   ```
   Add:
   ```
   [Service]
   Environment="PULSE_LOG_LEVEL=debug"
   ```

2. Restart and check logs:
   ```bash
   sudo systemctl daemon-reload
   sudo systemctl restart pulse-agent
   sleep 5
   journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"
   ```

This will show what the agent is actually doing when collecting S.M.A.R.T. data. Look for "Failed to collect S.M.A.R.T. data" or similar messages.

Also confirm smartctl works directly:
```bash
smartctl --scan
smartctl -a /dev/sda  # replace with an actual disk from the scan
```

**Comment by rcourtman** [comment]
Apologies for the confusion — there's no `--run-once` flag. That was incorrect.

To debug S.M.A.R.T. collection, temporarily enable debug logging in the running agent:

1. Edit the service:
   ```bash
   sudo systemctl edit pulse-agent
   ```
   Add:
   ```
   [Service]
   Environment="PULSE_LOG_LEVEL=debug"
   ```

2. Restart and check logs:
   ```bash
   sudo systemctl daemon-reload
   sudo systemctl restart pulse-agent
   sleep 5
   journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"
   ```

This will show what the agent is actually doing when collecting S.M.A.R.T. data. Look for "Failed to collect S.M.A.R.T. data" or similar messages.

Also confirm smartctl works directly:
```bash
smartctl --scan
smartctl -a /dev/sda  # replace with an actual disk from the scan
```

**Comment by MichiFr** [comment]
Ok, have done this, however, not really a progress, IMO.

No single line has been found, with
`journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"`


`smartctl --scan` gives

> /dev/sda -d scsi # /dev/sda, SCSI device
> /dev/nvme0 -d nvme # /dev/nvme0, NVMe device
> /dev/nvme1 -d nvme # /dev/nvme1, NVMe device
> /dev/nvme2 -d nvme # /dev/nvme2, NVMe device

Next command `smartctl -a /dev/nvme0` shows the same output as posted above, including temperatur (parts of the output).

> == START OF SMART DATA SECTION ===
> SMART overall-health self-assessment test result: PASSED
> 
> SMART/Health Information (NVMe Log 0x02)
> Critical Warning:                   0x00
> Temperature:                        56 Celsius
> Available Spare:                    100%
> Available Spare Threshold:          10%
> Percentage Used:                    0%
> Data Units Read:                    7,749,921 [3.96 TB]
> Data Units Written:                 66,026 [33.8 GB]
> Host Read Commands:                 19,025,479
> Host Write Commands:                133,635
> Controller Busy Time:               22
> Power Cycles:                       21
> Power On Hours:                     9,362
> Unsafe Shutdowns:                   2
> Media and Data Integrity Errors:    0
> Error Information Log Entries:      0
> Warning  Comp. Temperature Time:    0
> Critical Comp. Temperature Time:    0
> Temperature Sensor 1:               56 Celsius
> Temperature Sensor 2:               40 Celsius
> 
> Error Information (NVMe Log 0x01, 16 of 64 entries)
> No Errors Logged
> 
> Self-test Log (NVMe Log 0x06)
> Self-test status: No self-test in progress
> No Self-tests Logged

<img width="1398" height="348" alt="Image" src="https://github.com/user-attachments/assets/fc2d2453-db09-4872-a840-5795f5d3f483" />

FWIW, `systemctl restart pulse-agent; sleep 5; journalctl -u pulse-agent -n 200 --no-pager` shows lots of logs:

> Dec 26 14:11:51 elbe pulse-agent[954915]: {"level":"info","time":"2025-12-26T14:11:51+01:00","message":"Pulse Unified Agent stopped"}
> Dec 26 14:11:51 elbe systemd[1]: Stopping pulse-agent.service - Pulse Unified Agent...
> Dec 26 14:11:51 elbe systemd[1]: pulse-agent.service: Deactivated successfully.
> Dec 26 14:11:51 elbe systemd[1]: Stopped pulse-agent.service - Pulse Unified Agent.
> Dec 26 14:11:51 elbe systemd[1]: pulse-agent.service: Consumed 2.520s CPU time, 26M memory peak.
> Dec 26 14:11:51 elbe systemd[1]: Started pulse-agent.service - Pulse Unified Agent.
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","version":"v5.0.3","pulse_url":"http://192.168.0.10:7655","host_agent":true,"docker_agent":false,"kubernetes_agent":false,"proxmox_mode":true,"auto_update":true,"time":"2025-12-26T14:11:51+01:00","message":"Starting Pulse Unified Agent"}
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","addr":":9191","time":"2025-12-26T14:11:51+01:00","message":"Health/metrics server listening"}
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","time":"2025-12-26T14:11:51+01:00","message":"Command execution disabled (use --enable-commands to enable)"}
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","time":"2025-12-26T14:11:51+01:00","message":"Host agent module started"}
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","component":"host-agent","time":"2025-12-26T14:11:51+01:00","message":"Proxmox mode enabled, checking setup..."}
> Dec 26 14:11:51 elbe pulse-agent[965680]: {"level":"info","component":"host-agent","time":"2025-12-26T14:11:51+01:00","message":"Proxmox node already registered, skipping setup"}
> Dec 26 14:11:53 elbe pulse-agent[965680]: {"level":"info","component":"host-agent","time":"2025-12-26T14:11:53+01:00","message":"Server enabled command execution - starting command client"}
> Dec 26 14:11:53 elbe pulse-agent[965680]: {"level":"info","component":"command-client","time":"2025-12-26T14:11:53+01:00","message":"Connected and registered with Pulse command server"}

Anything else I could help with? E.g. providing some more logs or config files?

**Comment by rcourtman** [comment]
The environment variable should be `LOG_LEVEL`, not `PULSE_LOG_LEVEL`. The agent doesn't read `PULSE_LOG_LEVEL`.

Update the systemd override:
```bash
sudo systemctl edit pulse-agent
```

Change to:
```
[Service]
Environment="LOG_LEVEL=debug"
```

Then restart and check logs:
```bash
sudo systemctl daemon-reload
sudo systemctl restart pulse-agent
sleep 5
journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"
```

This should now show the actual S.M.A.R.T. collection activity. Looking for either success messages or errors like "smartctl not in PATH" or "Failed to list block devices".

**Comment by ddkedr** [comment]
@rcourtman Hi! Could you please clarify the install script URL? I can't install the agent :(

I took a generated link from http://192.168.10.195:7655/settings/agents page and getting this:

```
root@proxmox:~# curl -kfsSL http://192.168.10.195:7655/install.sh | sh -s -- --url http://192.168.10.195:7655 --token <token>
curl: (22) The requested URL returned error: 404

root@proxmox:~# curl -L http://192.168.10.195:7655/install.sh
Install script not found
root@proxmox:~# ping 192.168.10.195
PING 192.168.10.195 (192.168.10.195) 56(84) bytes of data.
64 bytes from 192.168.10.195: icmp_seq=1 ttl=64 time=0.037 ms
64 bytes from 192.168.10.195: icmp_seq=2 ttl=64 time=0.072 ms
64 bytes from 192.168.10.195: icmp_seq=3 ttl=64 time=0.088 ms
```

There is no script there.

I'm on freshly updated (from web-ui) 5.0.4

**Comment by rcourtman** [comment]
@ddkedr The `/install.sh` endpoint was returning 404 because the unified agent installer script is new in v5.0.x and wasn't present in older installations. When you update via the web UI, only the `pulse` binary gets replaced - the scripts directory isn't updated.

**Fix deployed (7b6613b)**: The endpoint now falls back to fetching the script directly from GitHub if it doesn't exist locally.

**Immediate workaround** (until you're on the next release):
```bash
curl -sSL https://raw.githubusercontent.com/rcourtman/Pulse/main/scripts/install.sh | sudo bash -s -- --url http://192.168.10.195:7655 --token <token>
```

This will be fixed in the next release - the endpoint will automatically proxy from GitHub if the local file is missing.

**Comment by ddkedr** [comment]
@rcourtman nice, thank you!

Didn't exactly work, but, I guess I'll just wait for the next release :)

```
root@proxmox:~# curl -fsSL https://raw.githubusercontent.com/rcourtman/Pulse/main/scripts/install.sh | bash -s -- --url http://192.168.10.195:7655 --t
oken <token>--interval 30s
[INFO] Detecting available platforms...
[INFO] Proxmox detected - enabling Proxmox integration
[INFO]   (use --disable-proxmox to skip)
[INFO] Monitoring configuration:
[INFO]   Host metrics: true
[INFO]   Docker/Podman: false
[INFO]   Kubernetes: false
[INFO]   Proxmox: true
[INFO] Downloading agent from http://192.168.10.195:7655/download/pulse-agent?arch=linux-amd64...
curl: (22) The requested URL returned error: 404
[ERROR] Download failed. Check URL and connectivity.
Press Enter to exit...
root@proxmox:~# 
```

BTW, what is the proper way to update if not via web UI? Couldn't find default root/pass for the pulse LXC...

**Comment by MichiFr** [comment]
> sudo systemctl daemon-reload
> sudo systemctl restart pulse-agent
> sleep 5
> journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"
> This should now show the actual S.M.A.R.T. collection activity. Looking for either success messages or errors like "smartctl not in PATH" or "Failed to list block devices".

Unfortunately this ticket has been closed, nevertheless my answer about the logs. Above command journalctl reveals those lines.

> journalctl -u pulse-agent -n 200 --no-pager | grep -i "smart\|disk\|block"
> Dec 27 20:59:25 elbe pulse-agent[2734809]: {"level":"debug","device":"sda","model":"WDC WD40EFPX-68C6CN0","temperature":34,"health":"PASSED","time":"2025-12-27T20:59:25+01:00","message":"Collected SMART data"}
> Dec 27 20:59:25 elbe pulse-agent[2734809]: {"level":"debug","device":"nvme2n1","model":"Samsung SSD 980 1TB","temperature":46,"health":"PASSED","time":"2025-12-27T20:59:25+01:00","message":"Collected SMART data"}
> Dec 27 20:59:25 elbe pulse-agent[2734809]: {"level":"debug","device":"nvme1n1","model":"Lexar SSD NM790 2TB","temperature":61,"health":"PASSED","time":"2025-12-27T20:59:25+01:00","message":"Collected SMART data"}
> Dec 27 20:59:25 elbe pulse-agent[2734809]: {"level":"debug","device":"nvme0n1","model":"Lexar SSD NM790 2TB","temperature":57,"health":"PASSED","time":"2025-12-27T20:59:25+01:00","message":"Collected SMART data"}
> Dec 27 20:59:25 elbe pulse-agent[2734809]: {"level":"debug","component":"host-agent","diskCount":4,"time":"2025-12-27T20:59:25+01:00","message":"Collected S.M.A.R.T. disk data"}

HDD temps still not available in Pulse v5.0.5, btw. agent updated automatically to v5.0.5, too

**Comment by MichiFr** [comment]
See my answers below.

1. _elbe_ is a PVE node installed on a physical machine, a Ugreen NAS. I've added this node using Settings > Platforms > Virtual Environment. Additionally I've installed a pulse agent. FWIW, I plan to rename this node to pve01, so elbe and pve01 are the same.
2. I do see physical disks under storage
3. It's not a standalone host, like a Synology NAS, it's the appropriate Proxmox node.

On screenshot, you additionally see a second node _pve02_, installed on another pyhsical machine.

Here I'm missing the temps under physical disks:

![Image](https://github.com/user-attachments/assets/9911217d-41ee-497d-ab25-f1aecd3f7eed)

**Comment by rcourtman** [comment]
@MichiFr Good news! I've implemented a fix that addresses this.

**The issue:** Your pulse-agent was collecting SMART disk temps correctly (as shown in the logs), but those temps weren't appearing in the **Physical Disks** view because that view uses Proxmox API data.

**The fix (d297c803):** When a host agent is linked to a Proxmox node, we now merge the agent's SMART temperature data into the Physical Disks view. This means:
- ✅ Your disk temps will appear in Physical Disks without needing to enable Proxmox SMART monitoring
- ✅ The agent's SMART data is used as a fallback when Proxmox doesn't provide disk temps
- ✅ Matching is done by WWN (most reliable), serial number, or device path

Additionally, commit a6bd05ce fixes displaying SMART temps in the **Hosts** page for standalone host agents.

Both fixes will be in the next release. Thanks for the follow-up!

**Comment by MichiFr** [comment]
> Both fixes will be in the next release. Thanks for the follow-up!

Thanks for your excellent service 👍

**Comment by MichiFr** [comment]
If I'm correct, this fix should already be available, currently on 5.0.7, Pulse and agents, the temps are still not visible, though.
