### ISSUE TITLE
Proxmox agent initialise wrong IP

### ISSUE THREAD

**Issue by eilko** [rcourtman/Pulse#929]
**Describe the bug**
Pulse is installed with IP 10.46.10.19 on proxmox host 10.46.10.41
When installing the agent on this host. It gets initialised on network 192.168.46.x instead of 10.46.10.x

**To Reproduce**
1. Install agent via cli on proxmox host
2. host is added to pulse, but with wrong IP that cannot communicate with Pulse

**Expected behavior**
Stick to the network Pulse can be reached

**Environment:**
 - Pulse Version: 5.05
 - Installation Type: ProxmoxVE LXC

**Additional context**
Network setup on proxmox host. Network Ring and Ceph are not able to communicate outside its network. 

<img width="1158" height="166" alt="Image" src="https://github.com/user-attachments/assets/eb44d06c-30c8-4581-bc51-2fefa39c0749" />

**Comment by rcourtman** [comment]
Pushed a potential fix (268697b).

The agent was using heuristic scoring to pick an IP (preferring 192.168.x.x over 10.x.x.x), but in your setup the 192.168.x.x network is the isolated Ring network, not the management network.

Now the agent first determines which local IP is actually used to connect to the Pulse server. It does this by checking which network interface routes to the Pulse URL, ensuring registration uses an IP that can actually communicate with Pulse.

Will be in the next release. To apply the fix once available:
1. Update to the new version
2. Delete the state file: `rm /var/lib/pulse-host-agent/proxmox-*-registered` 
3. Re-run the installer to trigger fresh registration

**Comment by eilko** [comment]
Fixed in 5.06

**Comment by geekon-now** [comment]
The problem is only partly resolved.
I had the similar issue previously, now the host agent is properly sending the data to the Pulse server, _but still the pulse server is fetching the data from the internal IPs of cluster._ which is not reachable form the private network IP eg. 10.x.x.x.

**See below the Pulse LXC log:**
`
Jan 08 14:14:51 M-Pulse pulse[128]: {"level":"info","component":"pulse-config","cluster":"node1","unhealthyEndpoints":["https://172.168.100.5:8006","https://172.168.100.3:8006","https://172.168.100.4:8006","https://172.168.100.2:8006","https://172.168.100.1:8006"],"count":5,"time":"2026-01-08T12:14:51Z","message":"Attempting to recover unhealthy cluster endpoints"}`

These above 172.x.x.x IPs are assigned to the Bonds(aggregated NICs) of the Nodes created for internal cluster commination. But all the Nodes in cluster have Vmbr0 configured on different bond, which have Internal 10.x.x.x. IPs which should be the IPs that the Pulse server has to fetch data from. **Also this is the IP(10.x.x.x.) that I provided during the proxmox setup in Pulse web GUI settings. But pulse is taking the other internal network IPs.**

<img width="518" height="182" alt="Image" src="https://github.com/user-attachments/assets/4335b20f-c73b-43d0-92c7-d84963031bf2" />

However the agent is sending the data correctly to the Pulse LXC server ip. Still the dashboard shows 'Degraded status (orange color) ' and shows Error: "Request timed out - Proxmox API may be slow or waiting on unreachable backend services." because of the reson I mentioned above. 

**Now, Is it possible to configure the IPs/network of the Nodes ourself in any config file or how to resolve it?**

**Comment by rcourtman** [comment]
@geekon-now Thanks for the detailed report. I understand the issue - the agent registration fix (268697b) addresses how agents determine their own IP, but there's a separate issue with how Pulse discovers cluster node endpoints.

**The problem:**
When Pulse detects a cluster, it queries `/cluster/status` which returns node IPs from the cluster's perspective. In multi-network setups, these are often internal ring/cluster IPs (like your 172.168.100.x) rather than management IPs (10.x.x.x).

**Current workaround:**
Edit your Pulse config file and manually override the cluster endpoints with the correct management IPs. Look for `clusterEndpoints` in your config.yaml.

**Feature request captured:**
We need a way to:
1. Allow manual endpoint IP overrides in the UI
2. Or detect which network Pulse should prefer based on the initial connection IP

Reopening this issue to track the cluster endpoint discovery problem separately from the agent registration issue.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by rcourtman** [comment]
Pushed a fix in commit d5c93fd2 that adds support for cluster endpoint IP overrides.

**What's new:**
- Added `IPOverride` field to cluster endpoints
- When set, Pulse uses the override IP instead of the auto-discovered cluster IP
- Connection code now uses `EffectiveIP()` which prefers override over auto-discovered

**How to use (until UI support is added):**
Edit your `nodes.json` (or the encrypted config) and add `IPOverride` to each cluster endpoint:

```json
"ClusterEndpoints": [
  {
    "NodeName": "node1",
    "IP": "172.168.100.5",
    "IPOverride": "10.1.1.5",
    ...
  }
]
```

Pulse will now connect to `10.1.1.5` instead of the auto-discovered `172.168.100.5`.

**Next steps:**
- UI support for editing IPOverride is still needed
- For now, manual config editing is required

Would appreciate confirmation that this resolves the connectivity issue once you've upgraded.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by rcourtman** [comment]
**Better fix pushed in commit bd1df9f9!**

Pulse now automatically detects and uses the correct management network IPs. Here's how it works:

1. When you add a cluster using `https://10.1.1.5:8006`, Pulse remembers that `10.1.1.x` is your management network
2. During cluster discovery, if a node reports an IP on a different subnet (like `172.168.100.6`), Pulse queries that node's network interfaces
3. If it finds an IP on the preferred subnet (like `10.1.1.6`), it automatically uses that instead

**No manual configuration required** - this should just work out of the box for most multi-network setups.

The manual `IPOverride` field is still available as an escape hatch if automatic detection doesn't work for your specific setup.

Would appreciate confirmation once you've upgraded!

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by geekon-now** [comment]
is it pushed to 5.0.11?. I just installed fresh and checked. But still the same.

<img width="405" height="175" alt="Image" src="https://github.com/user-attachments/assets/d93b755d-7b67-4b6e-81f7-731c8f2b8d0b" />

**Also, nodes.json is not found, i only found nodes.enc and its displays only junk so couldnt modify it.**

**Comment by rcourtman** [comment]
@geekon-now The automatic subnet preference fix (bd1df9f9) is in `main` but hasn't been released yet - 5.0.11 was released before these commits.

**Current status:**
- 5.0.11 = latest release (doesn't include the fix)
- The fix is in `main`, targeting the next release

**Options for now:**
1. **Wait for next release** - the fix will be included
2. **Build from main** - if you need it urgently:
   ```bash
   git clone https://github.com/rcourtman/Pulse.git
   cd Pulse && make build
   ```

**Regarding `nodes.enc`:**
The encrypted config (`nodes.enc`) is used when encryption is enabled. To use the manual `IPOverride` workaround with encrypted configs, you'd need to:
1. Delete `nodes.enc` 
2. Re-add the cluster through the UI
3. Edit the resulting config file before encryption

However, I'd recommend waiting for the next release since the automatic subnet detection should handle your case without manual configuration.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by geekon-now** [comment]
I updated to the new version release 5.0.13. Still the problem exists. 

<img width="620" height="459" alt="Image" src="https://github.com/user-attachments/assets/4572faa2-c425-4a83-9458-5573a37239ff" />

**Comment by rcourtman** [comment]
Thanks for testing 5.0.13. Looking at your screenshot, I can see:
- **Proxmox: Online** - Pulse can reach the Proxmox API directly
- **Pulse: Unreachable** - The node/agent can't connect back to Pulse

This suggests the agent is still reporting with the wrong IP (192.168.x instead of 10.x).

**Debugging steps:**

1. **Check which IP the agent is using:**
   On your Proxmox host, check the agent logs:
   ```bash
   journalctl -u pulse-agent -n 50 --no-pager | grep -i "ip\|register\|connect"
   ```

2. **Try the explicit ReportIP workaround:**
   Edit the agent service file:
   ```bash
   # Find where pulse-agent is configured
   systemctl cat pulse-agent
   
   # Edit to add --report-ip flag with your management IP
   # Add: --report-ip 10.46.10.41
   
   # Restart
   systemctl restart pulse-agent
   ```

3. **Or use the environment variable:**
   ```bash
   # Create override file
   mkdir -p /etc/systemd/system/pulse-agent.service.d/
   cat > /etc/systemd/system/pulse-agent.service.d/override.conf << 'OVERRIDE'
   [Service]
   Environment="PULSE_REPORT_IP=10.46.10.41"
   OVERRIDE
   
   systemctl daemon-reload
   systemctl restart pulse-agent
   ```

4. **Or remove and re-add the cluster:**
   The subnet preference logic runs during discovery. If the cluster was added before the fix:
   - Remove the cluster from Pulse settings
   - Re-add it using the 10.x IP
   - The new logic should auto-detect the correct IPs

Could you share the agent logs showing which IP it's trying to use? That will help narrow down whether this is a detection issue or something else.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by geekon-now** [comment]
The problem is not with the agent , the agent URL in log is correct IP.

**Only the Pulse Server is trying for different internal IPs.**

See below the **Pulse Server LXC** log:
` Jan 08 14:14:51 M-Pulse pulse[128]: {"level":"info","component":"pulse-config","cluster":"node1","unhealthyEndpoints":["https://172.168.100.5:8006","https://172.168.100.3:8006","https://172.168.100.4:8006","https://172.168.100.2:8006","https://172.168.100.1:8006"],"count":5,"time":"2026-01-08T12:14:51Z","message":"Attempting to recover unhealthy cluster endpoints"}`

There should not be 172.x.x.x above here right?
**Also the IPs shown in the Pulse GUI settings for the nodes also reflect the internal IPs are same as confirmed here in the logs.**

**Comment by rcourtman** [comment]
Found and fixed the root cause (commit b7f5cfde).

**The issue:**
When you add a cluster via the management network (10.x.x.x), the cluster API returns node IPs on the internal network (172.168.100.x). Pulse then tries to validate each node by connecting to those internal IPs - which fails because they're not routable.

The subnet preference logic was only applied for nodes that passed validation. But since validation failed (because it used unreachable IPs), the fallback path just stored the unreachable IPs without attempting to find better ones.

**The fix:**
The fallback path now applies the same subnet preference logic as the main path:
1. Queries node network interfaces via the initial working connection
2. Looks for an IP on the same network as your initial connection (10.x.x.x)
3. Sets `IPOverride` to use that IP instead

This should resolve the "unhealthyEndpoints" issue you're seeing with the 172.168.100.x addresses.

**To test:**
After updating to the next release, try re-adding your cluster. The log should now show:
```
Found preferred management IP for unvalidated cluster node
  node=<name> cluster_ip=172.168.100.x preferred_ip=10.x.x.x
```

**Comment by geekon-now** [comment]
**Thanks.  Now the issue is solved.** **But** the Proxmox tab takes hell a lot of time showing the "loading config.", what should be the reason?. is it try to check for updated here! [P.S. I don't have internet in that LXC]?

2) I have added proxmox pulse agent for 1 Node out of 3, does it require to add in all the three nodes or what is the implication?
3) How to add guest URLs for every node? now the Guest URL is same for all the nodes which I have given for node 1. 

<img width="275" height="67" alt="Image" src="https://github.com/user-attachments/assets/11671cb8-c2e1-4db3-a854-6dc31e7fd30c" />

<img width="1653" height="419" alt="Image" src="https://github.com/user-attachments/assets/735b42be-bb23-440f-9623-b176e605af37" />

**Comment by rcourtman** [comment]
@geekon-now Glad the IP issue is resolved! To answer your questions:

**1. "Loading config" delay**
This is likely checking for updates from GitHub when the Proxmox settings page loads. Without internet access, it will timeout before proceeding. This isn't critical functionality - the page should eventually load after the timeout. We should probably make this check non-blocking or skip it when internet isn't available.

**2. Agent on all nodes**
No, you don't need an agent on every node. The agent is optional - it provides additional metrics (host-level stats, guest ping) but the core Proxmox monitoring works via the API from a single connection point. 

Use cases for multiple agents:
- If you want host-level metrics from each node (CPU temp, disk I/O, etc.)
- If you want guest ping monitoring from multiple network vantage points

**3. Guest URLs per node**
Currently, the Guest URL setting applies cluster-wide. Each guest uses the same URL template. This is a known limitation.

Workaround: The Guest URL supports variables like `{vmid}`, `{name}`, etc. If your VMs have predictable naming that includes the node, you might be able to construct URLs that way.

Feature request noted: Per-node Guest URL configuration would be useful for setups where VMs are accessed through different gateways depending on their host node.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by rcourtman** [comment]
Resolved — management network auto-detection and PULSE_REPORT_IP support address the IP initialization issue.
