### ISSUE TITLE
Storage on Synology NAS calculated wrong

### ISSUE THREAD

**Issue by Twilek-de** [rcourtman/Pulse#953]
Pulse adds each directory again and again. So it reports 406 TB (I wish :-) ) of total capacity instead of 16 TB, which is true.

<img width="325" height="771" alt="Image" src="https://github.com/user-attachments/assets/bbf1fad2-3414-4d74-a81c-c3c505afaee6" />

**Comment by rcourtman** [comment]
Fixed in commit 29efafb8. 

The issue was that Synology DSM creates multiple mount points for shared folders (e.g., `/volume1/docker`, `/volume1/photos`) that all reside on the same underlying BTRFS volume. Each mount was reporting the same 16TB total, so Pulse was summing them all (4 shares × 16TB = 64TB displayed instead of 16TB).

The fix now deduplicates disks by tracking device + total combinations. When multiple mount points share the same device and report the same total capacity, only one is counted. The shallowest mountpoint (e.g., `/volume1` instead of `/volume1/docker`) is preferred.

This will be included in the next release. Please update your agent when the release is available and let me know if this resolves the issue.

**Comment by Twilek-de** [comment]
Updated to 5.0.8 (also updated the agent on the synology). It is better but still wrong. 

<img width="235" height="209" alt="Image" src="https://github.com/user-attachments/assets/e367d1bb-8cf6-45a6-887f-b51874828237" />

That is the real setup

<img width="1635" height="132" alt="Image" src="https://github.com/user-attachments/assets/bd3def17-87ba-421f-ad95-3574e2066779" />

**Comment by Twilek-de** [comment]
Ahh sorry, my bad, I was wondering about the 45 TB capacity and totally forgot that there is a big USB drive attached to the NAS which is used for backups and not for storage so that it doesn´t show up in the storage pool statistics. I guess pulse reports the right figures now after all. Thanks!
