### ISSUE TITLE
"Agent required" after updating to 5.0.6

### ISSUE THREAD

**Issue by jostrasser** [rcourtman/Pulse#971]
**Describe the bug**
After the update to 5.0.6 all agents started the update automatically.
Since the update I can see "Agent required" in the Proxmox VE nodes view, but they are running and collecting.

**To Reproduce**
1. Update to 5.0.6
3. See error

**Expected behavior**
Should report that the agent is working as expected to collect temp data

**Environment:**
 - Pulse Version: 5.0.6
 - Installation Type: Docker

**Additional context**

<img width="973" height="500" alt="Image" src="https://github.com/user-attachments/assets/9d7be21f-514c-47ac-876b-b09f7e707893" />

<img width="839" height="120" alt="Image" src="https://github.com/user-attachments/assets/61e41668-d537-4394-9425-aff186e1ce28" />

**Comment by rcourtman** [comment]
This should be fixed in commit 599fe1ab. The issue was that the frontend was matching host agents to PVE nodes by hostname only, which could fail if the hostname didn't match exactly.

The fix now uses the proper `linkedHostAgentId` relationship established by the backend, falling back to hostname matching only if no linked agent is found. This means if an agent is properly linked to a node (which happens automatically when the agent reports from the same machine), the "Via agent" badge should now display correctly.

Please update to the latest version and let me know if the issue persists.

**Comment by jostrasser** [comment]
@rcourtman I updated to 5.0.7 but the behaviour is still the same.

**Comment by jostrasser** [comment]
Same behavior on 5.0.9.
